sets.exported={
    left_ring="デジョンリング",
    item="闇の足具：ナ",
    left_ear="シェリダピアス",
    left_ear="マーケピアス+1",
    left_ring="エパミノダスリング",
    item="禁断の宝のカギ",
    item="モグチケット【赤】",
    sub="トーレット",
    left_ear="クリプティクピアス",
    item="ダイヤルキー#Ab",
    item="ガーゴイルの欠片",
    item="モグの預り帳【18】",
    item="モグの預り帳【27】",
    item="色褪せた鱗",
    item="ダイヤルキー#SP",
    item="モグの預り帳【16】",
    left_ear="電界の耳",
    item="リンクパール",
    sub={ name="マレヴォレンス", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    item="鹿ノ札",
    left_ring="守りの指輪",
    left_ring="Ｄ．デムリング",
    item="モグの預り帳【28】",
    item="互助会引換券・銅",
    item="魔王印章",
    head={ name="テーオンシャポー", augments={'Accuracy+22','"Triple Atk."+2','Phalanx +3',}},
    item="イグドリアの根",
    item="互助会引換券・銀",
    hands="ビウェグカフス",
    item="ガーゴイルの角",
    item="魔人印章",
    item="鋭い白石+1",
    item="鋭い白石+1",
    item="鋭い白石+1",
    item="モグの預り帳【25】",
    item="鋭い白石+1",
    item="禁断の宝のカギ",
    item="モグの預り帳【23】",
    item="ガーゴイルの眼",
    item="鋭い白石+1",
    item="タウルスの角",
    item="モグの預り帳【21】",
    item="パールサック",
    item="タウルスの翼",
    item="ガーゴイルの欠片",
    left_ear="ダークサイドピアス",
    item="武神の免罪符：両足",
    sub="クラーケンクラブ",
    item="ギル",
    body="ピュピルシャツ",
    item="G9Dアルミラー",
    range="アキヌフォート",
    item="シルバークランツ",
    sub="遺品短刀",
    feet="サッチブーツ",
    body="カウンセラーガーブ",
    head="エブルハット",
    sub={ name="ターティブ", augments={'Occ. atk. 2-4 times+12',}},
    body="ヴェディクコート",
    hands="カラパチョカフス",
    legs="エボンパンツ",
    body="カウントガーブ",
    sub={ name="ノビリス", augments={'Attack+5',}},
    left_ring="マリッジリング♀",
    head="ＣＡティアラ+1",
    item="パヌティエール",
    head={ name="ＨＡハット+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Avatar perpetuation cost" -5',}},
    back="フェリシタケープ+1",
    item="ギルドフライヤー",
    legs="ピュピルトラウザ",
    body="エブルコート",
    head="ミドラスヘルム+1",
    back={ name="ルディアノスマント", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    range="与一の弓",
    body={ name="ＨＡコート+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','Pet: Mag. Acc.+24',}},
    item="国教会発行結婚証明",
    left_ring="フェニアンリング",
    body="ウェディングドレス",
    head="ストローハット",
    body="アンフルローブ",
    body="ピュピルカミーサ",
    body="ＧＴコート+2",
    item="オーケストリオン",
    main="魔道士の杖",
    body="ブレスドブリオー",
    back="ネクサスケープ",
    left_ear="ネリチックピアス",
    body="調理師スモック",
    body="ノーブルチュニック",
    feet="ヒポメネソックス",
    hands="エブルカフス",
    hands="ＡＧブレーサー+2",
    feet="ウェディングブーツ",
    feet="ドリームブーツ+1",
    legs={ name="ＧＥスパッツ+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -3%','"Cure" spellcasting time -5%',}},
    hands="調理師グローブ",
    item="舞刀会の招待状",
    hands="ワークグローブ",
    hands="ノーブルミトン",
    range={ name="スパロウホーク+2", augments={'TP Bonus +1000',}},
    sub="リフキンガード",
    legs="ウェディングホーズ",
    hands="カウンセラーカフス",
    legs="パデシンスロップス",
    back="霊亀外套",
    feet="那伽脚絆",
    left_ear="ヒルディネアピアス",
    back={ name="ゴストファイケープ", augments={'Enfb.mag. skill +6','Enha.mag. skill +9','Mag. Acc.+9','Enh. Mag. eff. dur. +19',}},
    head="エボンハット",
    item="グリーンチップ",
    head="エブルカウビーン",
    item="裁縫カウンター",
    item="ヴァナクロック",
    feet="エブルサボ",
    item="ヒュームＦマネキン",
    left_ear="嫉妬の耳",
    item="調理カウンター",
    item="ガレーキッチン",
    item="アルザダールデスク",
    hands="エボンゲージ",
    legs={ name="テーオンタイツ", augments={'Accuracy+20 Attack+20','"Triple Atk."+2','DEX+10',}},
    sub="エクスカリパー",
    waist="ウィトフルベルト",
    head={ name="ヘルクリアヘルム", augments={'Rng.Acc.+24 Rng.Atk.+24','Crit.hit rate+4','STR+3','Rng.Acc.+12','Rng.Atk.+7',}},
    hands="コモドアガントリー",
    legs="ホワイトズボン",
    item="クーポンI-Seal",
    head="リラコサージュ",
    body={ name="ＧＥブリオー+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    body="ケロナブレザ",
    body="パペトリトベ",
    item="セフエジの皮",
    sub="イージス",
    main="ベオルクソード",
    item="ククルカンの皮",
    hands="パペトリダスタナ",
    item="ウィルドクロス",
    item="黒の残魂",
    legs="フェーミナサブリガ",
    item="エスカイト鉱石",
    item="デフィアントの襟巻",
    item="錆びた認識票",
    item="錆びた認識票",
    feet="パペトリバブーシュ",
    item="ククルカンの皮",
    sub="ズーゾーウグリップ",
    item="デフィアントの襟巻",
    feet={ name="ＧＥガロッシュ+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -3%','"Cure" spellcasting time -5%',}},
    head={ name="ＧＥカウビーン+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    hands={ name="オトミグローブ", augments={'HP+30','MP+30','MP+30',}},
    body={ name="ウェーザーローブ+1", augments={'MP+120',}},
    item="不浄なる白銀",
    main={ name="ケラウノス", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Elemental Siphon"+25','INT+21',}},
    sub="イズカリ",
    item="ヘパテゾインゴット",
    item="冥王の爪",
    sub="チャームステッキ",
    item="シフマクラメ",
    sub="ミラクルステッキ",
    item="バズテヴィアの翅",
    item="黒の残魂",
    item="獣人勲章",
    body="ハートエプロン+1",
    hands={ name="アデマリスト+1", augments={'AGI+12','Rng.Acc.+20','Rng.Atk.+20',}},
    body="シルヴィシャツ",
    head="ローハイドマスク",
    sub="ニオビッドストラップ",
    feet="インスピリトブーツ",
    range="Ｐ．ストリンガーII",
    item="ラズのなめし革",
    sub="ラファエルロッド",
    back="ルーパインケープ",
    item="ペネロペ織物",
    left_ear="ノーヴィアピアス",
    left_ear="スリオスイヤリング",
    legs="ダッシングサブリガ",
    item="ヴァルカン鉱",
    neck="アイドロチャーム+1",
    ammo="ハイドロセラ",
    left_ear="ハメティックピアス",
    item="シフの髪",
    item="アクヴァンの翼",
    sub="オハン",
    item="プロビッドの体液",
    neck="エディネクラス",
    item="グレーリキッド+2",
    ammo="エリストーム",
    waist="テンパスフジット",
    item="忘れ去られた感触",
    item="ソベランの毛皮",
    left_ear="ライムアイスピアス",
    sub="サンダン",
    waist="オネイロスロープ",
    left_ring="アペートリング",
    back={ name="ガンスリンガマント", augments={'Enmity-4','"Mag.Atk.Bns."+1','"Phantom Roll" ability delay -5','Weapon skill damage +1%',}},
    left_ring="ヴェンジフルリング",
    item="黒ずんだ認識票",
    item="アブダルスの染料",
    item="マスイルの装甲",
    item="プロビッドの体液",
    item="マスイルの角",
    item="イグドリアの根",
    item="デフィアントの襟巻",
    item="冥王の爪",
    item="バズテヴィアの針",
    item="アブダルスの糸",
    item="モグの預り帳【09】",
    item="ヘヴィメタル",
    item="アブダルスの水油",
    item="モグの預り帳【01】",
    item="アブダルスの金粉",
    item="ワクタザの冠羽",
    item="モグの預り帳【03】",
    item="フィルの堅甲",
    item="アブダルスの樹脂",
    item="アンブラルマロウ",
    item="ねばねばした金塊",
    item="Ａ．チケット：足+1",
    item="アブダルスナゲット",
    item="Ａ．トークン：指",
    item="アブダルスの樹脂",
    item="ロックフィンのヒレ",
    item="冥応の鎖",
    item="アブダルスの水油",
    item="Ａ．チケット：頭+1",
    item="アケオメの魂",
    item="錆びた認識票",
    item="アブダルスオーブ",
    item="アブダルスの樹脂",
    item="Ａ．チケット：指",
    item="Ａ．トークン：足+1",
    item="アブダルスメタル",
    main={ name="オータス", augments={'Accuracy+70','Pet: Accuracy+70','Pet: Haste+10%',}},
    item="グレーリキッド+2",
    head={ name="カイロンハット", augments={'Rng.Atk.+24','Mag. Acc.+22 "Mag.Atk.Bns."+22','"Refresh"+2','Accuracy+8 Attack+8',}},
    range="Ｐ．ストリンガー+1",
    item="アブダルスファイバ",
    item="冥界の鎖",
    item="アブダルスアニマ",
    item="ロックフィンの鋭歯",
    item="アブダルスマター",
    hands="カイロングローブ",
    item="Ａ．トークン：脚+1",
    item="Ａ．チケット：背",
    ammo="ルブリカント+3",
    item="モグチケット【銀】",
    item="ジュラルミン板：裁",
    item="Ａ．チケット：手+1",
    item="アブダルスエギーユ",
    item="ダークマター",
    item="Ａ．チケット：武器",
    item="グレーリキッド+2",
    item="Ａ．チケット：胴+1",
    item="モグチケット【赤】",
    item="Ａ．トークン：手+1",
    item="Ａ．トークン：頭+1",
    legs={ name="カイロンホーズ", augments={'Accuracy+6','Pet: Mag. Acc.+22','"Refresh"+2','Mag. Acc.+4 "Mag.Atk.Bns."+4',}},
    sub="ペーパーナイフ",
    item="インフィニティコア",
    item="カラボスの小石",
    item="セフエジの爪",
    sub="マリグナスソード",
    item="海神の免罪符：両脚",
    item="ルテニム鉱",
    legs="ボーンサブリガ",
    item="アブダルスの染料",
    main="ヅェーシシュの薙刀",
    item="ガタンブ原木",
    item="モグの預り帳【10】",
    item="アブダルスの金粉",
    waist="月虹帯+1",
    item="神気のグリモア",
    item="イグドリア原木",
    back={ name="ビスシアスマント", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Pet: Haste+10',}},
    item="桂馬の小札",
    item="大学者のカード",
    item="黒の残魂",
    item="バイルエリクサー+1",
    item="古い袋【緑魂石】",
    item="特上スシ",
    item="大吟遊詩人のカード",
    item="ブッキスの翼",
    item="大召喚士のカード",
    item="香車の小札",
    item="パナケイア",
    item="モグの預り帳【22】",
    item="消化薬",
    item="古い袋【黒魂石】",
    item="パナケイア",
    item="歩兵の小札",
    feet="ムセスクラッコー+1",
    item="大風水士のカード",
    item="パナケイア",
    item="イカロスウィング",
    left_ring="初志の指輪：裁縫",
    item="毒消し",
    item="ワークスエーテル",
    item="ワークスエーテル",
    item="ダイヤルキー#Ab",
    item="アブダルスの焼印",
    item="古い袋【黒魂石】",
    item="モグの預り帳【13】",
    item="プリズムパウダー",
    item="銀将の小札",
    item="メイズタビュラM01",
    item="ダイヤルキー#SP",
    item="呪符デジョン",
    item="ココナッツラスク",
    item="カルボナーラ",
    item="漁師風近東鍋",
    item="赤餅",
    item="聖水",
    item="ハイエリクサー",
    item="大海賊のカード",
    item="プリズムパウダー",
    item="味噌ラーメン",
    item="モグの預り帳【11】",
    item="万能薬",
    item="忍だすき【鈎縄】",
    item="闇の塊",
    item="大白魔道士のカード",
    item="特上スシ",
    item="忍だすき【紙兵】",
    item="バイルエリクサー",
    item="レッドカレーパン",
    item="ワークスエーテル",
    item="古い袋【黒魂石】",
    item="モグの預り帳【04】",
    item="サイレントオイル",
    item="古い袋【黒魂石】",
    item="モグチケット【赤】",
    item="トロピカルクレープ",
    item="古い袋【黒魂石】",
    item="モグの預り帳【19】",
    item="ヴァーミリオンの翅",
    item="ワークスエーテル",
    item="万能薬",
    item="白餅",
    item="寄せ鍋",
    item="忍だすき【鹿】",
    item="味噌ラーメン+1",
    item="ワークスエーテル",
    item="ワークスエーテル",
    item="大魔導剣士のカード",
    item="キトロマカロン",
    item="万能薬",
    item="ワークスエーテル",
    item="モグの預り帳【06】",
    ammo="ホクスボクアロー",
    item="トロピカルクレープ",
    item="大赤魔道士のカード",
    sub="アーンダガー",
    sub={ name="マレヴォレンス", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+8','"Fast Cast"+5',}},
    feet={ name="ヘルクリアブーツ", augments={'STR+3','"Mag.Atk.Bns."+25','Accuracy+14 Attack+14','Mag. Acc.+16 "Mag.Atk.Bns."+16',}},
    neck="サクロゴルゲット",
    sub="燻竹刀",
    main="バウンティシックル",
    sub="ペルーン+1",
    neck="イスクルゴルゲット",
    sub="ウトゥグリップ",
    sub={ name="ロスタム", augments={'Path: C',}},
    legs={ name="ヘルクリアトラウザ", augments={'Pet: STR+2','"Occult Acumen"+3','"Treasure Hunter"+2','Accuracy+19 Attack+19',}},
    legs="ゾアサブリガ+1",
    body="霊亀大袖",
    body={ name="ヘルクリアベスト", augments={'Enmity+1','Accuracy+2 Attack+2','Phalanx +3','Mag. Acc.+10 "Mag.Atk.Bns."+10',}},
    range="フォーマルハウト",
    back={ name="カムラスマント", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    range="ガストラフェテス",
    range={ name="アナーキー+2", augments={'Delay:+60','TP Bonus +1000',}},
    main="ロスシックル",
    range="アルマゲドン",
    ammo="クロノアロー",
    sub="トゥワシュトラ",
    main="アーンスピア",
    head="オショシマスク+1",
    head={ name="テーオンシャポー", augments={'"Snapshot"+5','"Snapshot"+5',}},
    range="アナイアレイター",
    body="オショシベスト+1",
    sub="トレイニービュラン",
    hands="オショシグローブ+1",
    hands={ name="テーオングローブ", augments={'"Mag.Atk.Bns."+18','"Snapshot"+5','"Snapshot"+5',}},
    legs={ name="テーオンタイツ", augments={'"Mag.Atk.Bns."+19','"Snapshot"+5','"Snapshot"+4',}},
    main="打刀",
    legs="オショシトラウザ+1",
    ammo="ライヴブレット",
    main="ハピスタッフ",
    sub={ name="タミングサリ", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    range="ガーンデーヴァ",
    feet="オショシレギンス+1",
    waist="イェマヤベルト",
    waist="インパルスベルト",
    feet="ＳＫジャンボー+1",
    waist="レフォシレストーン",
    back={ name="アラウナスケープ", augments={'MP+60','Eva.+20 /Mag. Eva.+20','"Fast Cast"+10',}},
    back={ name="ルッフケープ", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Haste+10',}},
    feet={ name="テーオンブーツ", augments={'"Mag.Atk.Bns."+19','"Snapshot"+5','"Snapshot"+5',}},
    range="デスペナルティ",
    back={ name="ベレナスケープ", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    left_ring="エアリーリング",
    waist="グルンフェルロープ",
    left_ring="Ｄ．ホラリング",
    neck={ name="コモドアチャーム+2", augments={'Path: A',}},
    sub="ヌスクシールド",
    left_ear="マーケピアス+1",
    left_ring="ルザフリング",
    neck="王将の首飾り",
    legs={ name="アデマケックス+1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    back={ name="カムラスマント", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    left_ring="ヒギの指輪",
    sub="ティシュトライヤ",
    sub="プレイタシールド",
    back={ name="メシストピンマント", augments={'Cap. Point+50%','MP+17','Mag. Acc.+1','DEF+4',}},
    item="袋【薄い白石+1】",
    main={ name="ラシ", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    head="拡大眼鏡",
    item="ビーナスオーブ",
    range="オウレオール",
    item="巨大な大腿骨",
    body="裁縫師エプロン",
    item="コウモリの翼",
    item="反魂樹の根",
    item="地霊の免罪符：両手",
    item="武王の免罪符：両脚",
    back={ name="タラナスケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    neck="裁縫師トルク",
    item="海王の免罪符：両手",
    item="トゥクク白貝貨",
    item="ランスウッド原木",
    left_ring="クラフマスタリング",
    item="レリックアイアン",
    item="巨大なサレコウベ",
    feet={ name="ヘルクリアブーツ", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Crit. hit damage +1%','INT+2','Mag. Acc.+4','"Mag.Atk.Bns."+13',}},
    left_ring="エンドースリング",
    neck="召喚士の首輪+2",
    left_ring="アーテフィサリング",
    neck={ name="ソーサラストール+2", augments={'Path: A',}},
    sub={ name="ミョルニル", augments={'DMG:+8',}},
    left_ring="トリゼックリング",
    hands={ name="ＰＩミトン+3", augments={'Enhances "Martyr" effect',}},
    sub="クトゥルブナイフ",
    feet={ name="ＰＩダックビル+3", augments={'Enhances "Afflatus Solace" effect',}},
    head={ name="マーリンフード", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst dmg.+10%','INT+4','Mag. Acc.+7',}},
    head="バヤミハット",
    body="バヤミローブ",
    legs={ name="マーリンシャルワ", augments={'Mag. Acc.+18 "Mag.Atk.Bns."+18','Magic burst dmg.+9%','MND+8','Mag. Acc.+8','"Mag.Atk.Bns."+13',}},
    neck={ name="バードチャーム+2", augments={'Path: A',}},
    hands="バヤミカフス",
    legs="バヤミスロップス",
    back={ name="タラナスケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    feet={ name="マーリンクラッコー", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst dmg.+10%','INT+10',}},
    feet="バヤミサボ",
    body={ name="マーリンジュバ", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Conserve MP"+4','Mag. Acc.+14','"Mag.Atk.Bns."+15',}},
    waist="王将の帯",
    waist="オステリベルト+1",
    feet={ name="マーリンクラッコー", augments={'"Mag.Atk.Bns."+17','Pet: "Dbl. Atk."+2','"Treasure Hunter"+2','Accuracy+8 Attack+8',}},
    left_ring="Ｄ．メアリング",
    sub="スエースストラップ",
    hands="王将の手袋",
    back={ name="スセロスケープ", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','"Fast Cast"+10',}},
    main={ name="グリオアヴァール", augments={'Magic burst dmg.+4%','INT+19','Mag. Acc.+20','"Mag.Atk.Bns."+24',}},
    sub="ヤグルシュ",
    head={ name="テルキネキャップ", augments={'Mag. Evasion+23','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    sub={ name="タマシチ", augments={'Occ. atk. twice+8','Enmity-10',}},
    feet="ＡＺゲートル+1",
    head="ムセスターバン+1",
    back={ name="インタラアスケープ", augments={'Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10',}},
    head={ name="マーリンフード", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Mag. crit. hit dmg. +4%','INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+15',}},
    head="妖蟲の髪飾り+1",
    body="ヴリコダラジュポン",
    legs="ＡＢパンツ+1",
    legs={ name="サイクロスラッパ", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    back={ name="ベレナスケープ", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
    body="ＧＯチュニック+1",
    legs={ name="ＧＥスパッツ+1", augments={'Phys. dmg. taken -4%','Song spellcasting time -5%',}},
    body="ピンガチュニック+1",
    head="タリアターバン+2",
    legs="エアスロップス+1",
    back={ name="カムラスマント", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%',}},
    body={ name="テルキネシャジュブ", augments={'Mag. Evasion+25','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    range={ name="デュンナ", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    body="ＡＢガウン+1",
    body="ムセスマンティル+1",
    hands="ＡＺグローブ+1",
    hands="ＧＯミテーヌ+3",
    hands={ name="テルキネグローブ", augments={'Mag. Evasion+23','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    hands="ムセスゲージ+1",
    body="タリアマンティル+2",
    ammo="インカントストーン",
    legs="ピンガズボン+1",
    feet="ＧＯサンダル+1",
    body={ name="マーリンジュバ", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Magic burst dmg.+9%','DEX+1','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    head={ name="ＡＭコイフ+1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body="エアウプランド+1",
    ammo="サバントテーシス",
    legs={ name="ＡＭスロップス+1", augments={'INT+12','Elem. magic skill +20','Dark magic skill +20',}},
    body="トワイライトプリス",
    legs={ name="ＢＡパンツ+1", augments={'Enhances "Mending Halation" effect',}},
    legs={ name="テルキネブラコーニ", augments={'Mag. Evasion+25','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    legs="ＧＯパンツ+3",
    sub="イドリス",
    legs={ name="マーリンシャルワ", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Occult Acumen"+9','INT+14','Mag. Acc.+11','"Mag.Atk.Bns."+12',}},
    neck="ボルトサージトルク",
    head="ＡＢボネット+1",
    feet={ name="テルキネピガッシュ", augments={'Mag. Evasion+24','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    left_ear="驕慢の耳",
    left_ear="バーカロルピアス",
    feet="ＡＢローファー+1",
    body={ name="ＢＡチュニック+1", augments={'Enhances "Bolster" effect',}},
    feet={ name="ＡＭネール+1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    head="エアハット+1",
    legs="タリアサラウィル+2",
    head={ name="ＰＤボード+3", augments={'Enh. "Altruism" and "Focalization"',}},
    waist="チャネラーストーン",
    feet="ＴＥダックビル+3",
    head={ name="ヴァニヤフード", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    head="ビファウルクラウン",
    hands={ name="レイライングローブ", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    left_ear="セサンスピアス",
    hands="ＡＢブレーサー+1",
    legs="ムセスサラウィル+1",
    waist="ジーゲルサッシュ",
    back={ name="龍脈の外套", augments={'Geomancy Skill +10','Indi. eff. dur. +14','Pet: Damage taken -3%','Damage taken-3%',}},
    back={ name="コンベイケープ", augments={'Summoning magic skill +5','Pet: Enmity+14','Blood Pact ab. del. II -3',}},
    left_ear="フリオミシピアス",
    sub="クレリストラップ+1",
    neck={ name="スカウトゴルゲ+2", augments={'Path: A',}},
    feet="タリアクラッコー+2",
    head="ＡＺフード+1",
    hands={ name="ＡＭゲージ+1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body={ name="ＡＭダブレット+1", augments={'MP+80','"Mag.Atk.Bns."+25','"Fast Cast"+4',}},
    hands="タリアゲージ+2",
    body={ name="ヴァニヤローブ", augments={'MND+10','Spell interruption rate down +15%','"Conserve MP"+6',}},
    feet={ name="カイロンスリッパー", augments={'Pet: Mag. Acc.+29','Accuracy+25','"Refresh"+2','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    hands={ name="カイロングローブ", augments={'DEX+4','Phys. dmg. taken -2%','"Refresh"+2','Mag. Acc.+10 "Mag.Atk.Bns."+10',}},
    feet={ name="ヴァニヤクロッグ", augments={'"Cure" potency +5%','"Cure" spellcasting time -15%','"Conserve MP"+6',}},
    back={ name="アラウナスケープ", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10',}},
    back="スイスケープ+1",
    feet={ name="ＢＡサンダル+3", augments={'Enhances "Radial Arcana" effect',}},
    item="モグの預り帳【12】",
    sub="クスタウィ+1",
    sub="タンモガイ+1",
    item="白虎印章の欠片",
    item="イムルの大箱",
    item="イグノアの大箱",
    item="ダルスの大箱",
    item="トリルの大箱",
    main="クワ",
    legs="カスタムパンツ",
    item="リッジの大箱",
    back="ナントセルタケープ",
    body={ name="パスーアダブレット", augments={'DEX+7','AGI+10','"Recycle"+15',}},
    legs="メンヒトズボン",
    sub={ name="ヴァンピリズム", augments={'STR+10','INT+10','"Occult Acumen"+10','DMG:+15',}},
    back={ name="ロスメルタケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    legs="カルメカサブリガ",
    head={ name="ヘルクリアヘルム", augments={'Rng.Acc.+25 Rng.Atk.+25','Weapon skill damage +2%','STR+14','Rng.Atk.+2',}},
    range="キラーボウ",
    body="エブルブリオー",
    hands="オーヴェイルカフス",
    hands="エブルグローブ",
    item="モグの預り帳【15】",
    body={ name="ＰＩトベ+1", augments={'Enhances "Overdrive" effect',}},
    feet={ name="テーオンブーツ", augments={'Spell interruption rate down -10%',}},
    hands="鍛冶師グローブ",
    left_ear="サバントピアス",
    body={ name="ウィッチングローブ", augments={'MP+50','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Refresh"+1',}},
    item="モグの預り帳【08】",
    hands="アヤオゲージ",
    item="モグの預り帳【17】",
    range="コンペンセーター",
    head="コサージュ",
    body="ジョディシャツ",
    sub={ name="ソールスティス", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    feet="エブルブーツ",
    main="トライアルブレード",
    sub={ name="シンドリ", augments={'Accuracy+50','Attack+30','"Dbl.Atk."+5',}},
    head="ハルスハット+1",
    left_ear="ノーヴィオピアス",
    left_ring="鳥王の指輪+1",
    item="グラムクの大箱",
    body="ムンムジャケット+1",
    hands="カスタムＦグローブ",
    body="アクトン",
    main="マリグナスポール",
    ammo="銀銭",
    body="マンドラシャツ",
    sub="メルクリウスクリス",
    body="コシートップ+1",
    item="モグの預り帳【20】",
    feet="ＴＨブーツ+1",
    item="モグの預り帳【14】",
    left_ear="シグナルパール",
    neck="蓐収首鎖",
    feet="ケロナブーツ+1",
    left_ear="エナベートピアス",
    item="ドリームコッファー",
    left_ring="カコエシクリング",
    left_ear="玄冥耳飾り",
    body="ウドランシャツ",
    left_ring="パトリシアスリング",
    sub="エクスカリバー",
    item="モグの預り帳【02】",
    sub="玄冥盾",
    legs="ウドランパンツ",
    back="テンパードケープ+1",
    feet="ウドランブーツ",
    sub="シャープソード",
    neck="チョコボホイッスル",
    feet="パスーアゲートル",
    body="セイズルコタルディ",
    body="シャンゴローブ",
    feet="セルペンテスサボ",
    feet="オーヴェイルスリエ",
    main={ name="エーティル", augments={'Accuracy+70','Mag. Evasion+50','Weapon skill damage +10%',}},
    left_ring="エチャドリング",
    main={ name="エスピリトゥス", augments={'Summoning magic skill +15','Pet: Mag. Acc.+30','Pet: Damage taken -4%',}},
    back={ name="スセロスケープ", augments={'DEX+20','Accuracy+20 Attack+20','Mag. Acc.+10','"Dual Wield"+10',}},
    head={ name="マーリンフード", augments={'Pet: Mag. Acc.+24 Pet: "Mag.Atk.Bns."+24','Blood Pact Dmg.+9','Pet: Mag. Acc.+7',}},
    head="ＣＮホーン+1",
    body={ name="マーリンジュバ", augments={'Pet: Mag. Acc.+24 Pet: "Mag.Atk.Bns."+24','Blood Pact Dmg.+10','Pet: STR+3',}},
    body={ name="ＧＬダブレット+1", augments={'Reduces Sp. "Blood Pact" MP cost',}},
    body="ＡＣガウン+3",
    body="ＣＮダブレット+3",
    hands={ name="ＧＬブレーサー+1", augments={'Inc. Sp. "Blood Pact" magic burst dmg.',}},
    hands="ラマスミトン+1",
    legs={ name="ＧＬスパッツ+1", augments={'Increases Sp. "Blood Pact" accuracy',}},
    legs={ name="ＡＰズボン+1", augments={'Pet: STR+20','Blood Pact Dmg.+14','Pet: "Dbl. Atk."+4',}},
    legs="ＢＣスパッツ+1",
    head={ name="ＰＩキャップ+3", augments={'Enhances "Devotion" effect',}},
    feet={ name="ＧＬピガッシュ+1", augments={'Inc. Sp. "Blood Pact" magic crit. dmg.',}},
    head={ name="ＡＰクラウン+1", augments={'MP+80','Pet: Attack+35','Blood Pact Dmg.+8',}},
    waist="インカーネトサッシュ",
    back={ name="コンベイケープ", augments={'Summoning magic skill +3','Pet: Enmity+7','Blood Pact Dmg.+4',}},
    left_ear="エスパーピアス",
    left_ring="フェルボルリング",
    head={ name="ＧＬホーン+1", augments={'Enhances "Astral Flow" effect',}},
    body="ＢＣダブレット+1",
    hands="アステリアミトン+1",
    main={ name="グリオアヴァール", augments={'Blood Pact Dmg.+7','Pet: INT+9','Pet: Mag. Acc.+20','Pet: "Mag.Atk.Bns."+25',}},
    legs="アシドゥイズボン+1",
    feet="ＢＣピガッシュ+1",
    body="ＢＲジュスト+3",
    waist="ルセデティサッシュ",
    left_ear="エヴァンズピアス",
    left_ring="エボカーリング",
    main="ニルヴァーナ",
    head={ name="ＢＩラウンドリト+3", augments={'Enhances "Con Anima" effect',}},
    sub="ヴォックスグリップ",
    left_ear="ゲロスピアス",
    neck="コーラーペンダント",
    feet={ name="ＡＰパンプス+1", augments={'MP+80','Pet: Attack+35','Blood Pact Dmg.+8',}},
    hands={ name="マーリンダスタナ", augments={'Pet: Mag. Acc.+25 Pet: "Mag.Atk.Bns."+25','Blood Pact Dmg.+8','Pet: DEX+7','Pet: "Mag.Atk.Bns."+10',}},
    body={ name="ＰＩブリオー+3", augments={'Enhances "Benediction" effect',}},
    left_ear="サモニングピアス",
    hands={ name="ＧＥゲージ+1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    back={ name="ベレナスケープ", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','Weapon skill damage +10%',}},
    sub="エンキストラップ",
    head={ name="テルキネキャップ", augments={'"Elemental Siphon"+35',}},
    sub="エランストラップ+1",
    hands={ name="ＢＩカフス+3", augments={'Enhances "Con Brio" effect',}},
    back={ name="アラウナスケープ", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10',}},
    legs={ name="レンゴパンツ", augments={'INT+5','Mag. Acc.+4','"Mag.Atk.Bns."+1','"Refresh"+1',}},
    hands="ＢＲカフス+3",
    legs="ＴＥパンタロン+3",
    body={ name="テルキネシャジュブ", augments={'"Elemental Siphon"+30',}},
    hands={ name="テルキネグローブ", augments={'"Elemental Siphon"+30',}},
    neck="水影の首飾り",
    back={ name="カムラスマント", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10',}},
    feet="ＣＮピガッシュ+3",
    left_ring="ヴァラールリング+1",
    waist="神術帯+1",
    waist="ルーミネリサッシュ",
    waist="アサビクサッシュ+1",
    waist="イーサベルト",
    waist="ルミネートサッシュ",
    waist="オリンポスサッシュ",
    waist="カッソサッシュ",
    waist="ニヌルタサッシュ",
    waist="八輪の帯",
    left_ring="スティキニリング+1",
    legs={ name="テルキネブラコーニ", augments={'"Elemental Siphon"+35',}},
    legs={ name="エンタイサーパンツ", augments={'MP+50','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Pet: Damage taken -5%',}},
    head="ＥＢキャップ+1",
    feet="ＢＲスリッパー+3",
    body="ＥＢブリオー+1",
    hands="ＥＢミトン+1",
    legs={ name="ＰＩパンタロン+3", augments={'Enhances "Afflatus Misery" effect',}},
    range={ name="リノス", augments={'Accuracy+15','Weapon skill damage +3%','Quadruple Attack +3',}},
    legs="ＥＢパンタロン+1",
    feet="ＥＢダックビル+1",
    head="ＢＣホーン+1",
    body={ name="ＡＰダルマティカ+1", augments={'Summoning magic skill +20','Enmity-6','Pet: Damage taken -4%',}},
    body={ name="ＢＩジュストコル+3", augments={'Enhances "Troubadour" effect',}},
    feet={ name="マーリンクラッコー", augments={'Pet: Mag. Acc.+19 Pet: "Mag.Atk.Bns."+19','Blood Pact Dmg.+10','Pet: AGI+9','Pet: Mag. Acc.+10',}},
    sub={ name="クェラーロッド", augments={'MP+80','"Cure" potency +15%','Enmity-5',}},
    back={ name="ラプソドスケープ", augments={'HP+29','Mag. Acc.+5','Enmity-6',}},
    sub="ベニフィクス",
    main={ name="アーカI", augments={'Light Affinity: Magic Accuracy+1','Light Affinity: Magic Damage+6 Light Affinity: Casting time-14%',}},
    back={ name="オーグマケープ", augments={'DEX+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    ammo="エスパーストーン+1",
    ammo="ヘイストピニオン+1",
    ammo="ホミリアリ",
    ammo="ペムフレドタスラム",
    head="インヤガティアラ+2",
    sub="カルミナス",
    sub={ name="玄武盾", augments={'"Cure" potency +5%','"Cure" spellcasting time -6%','MP+27',}},
    neck="月虹の呼び子+1",
    sub={ name="アスクレピウス", augments={'Path: C',}},
    hands={ name="ファナチクグローブ", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    body={ name="ケカスブリオー+1", augments={'MP+80','"Cure" potency +6%','"Conserve MP"+7',}},
    hands="ダイナスティミトン",
    waist="スクリミルコード+1",
    left_ring="隠者の指輪+1",
    sub="アムラピシールド",
    main={ name="ムサ", augments={'Path: C',}},
    feet="ヘラルドゲートル",
    range={ name="リノス", augments={'Accuracy+15','"Fast Cast"+4','AGI+6',}},
    legs={ name="ケカスタイツ+1", augments={'MP+80','"Cure" spellcasting time -7%','Enmity-6',}},
    neck="インカンタートルク",
    body={ name="ヘルクリアベスト", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Enmity-3','AGI+3','Mag. Acc.+5','"Mag.Atk.Bns."+12',}},
    back="ソレムニティケープ",
    back={ name="ナントセルタケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    range="ブラーハープ+1",
    back={ name="メンディングケープ", augments={'Healing magic skill +10','Enha.mag. skill +8','Mag. Acc.+8',}},
    ammo="ストンチタスラム+1",
    left_ear="メンデカントピアス",
    left_ear="エテオレートピアス",
    left_ear="朝露の耳飾",
    neck={ name="バグアチャーム+2", augments={'Path: A',}},
    left_ear="エンチャンピアス+1",
    left_ear="アンドアーピアス",
    back="フィフォレケープ+1",
    left_ring="ヴァラールリング+1",
    left_ear="ロケイシャスピアス",
    waist="ビショップサッシュ",
    left_ear="ミミルピアス",
    left_ring="女王の指輪+1",
    left_ring="女王の指輪+1",
    back={ name="ブックワームケープ", augments={'INT+1','MND+1','Helix eff. dur. +20','"Regen" potency+10',}},
    waist="句芒の帯",
    back={ name="カンペストレケープ", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20',}},
    left_ring="メネロスリング",
    left_ring="ハオマリング",
    left_ring="プロリクスリング",
    hands="インヤガダスタナ+2",
    left_ring="スティキニリング+1",
    head={ name="ヘルクリアヘルム", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Crit. hit damage +1%','STR+8','Mag. Acc.+7','"Mag.Atk.Bns."+14',}},
    ammo="王将の玉",
    body="インヤガジュバ+2",
    feet="インヤガクラッコ+2",
    back={ name="ベレナスケープ", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    back={ name="ルッフケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Magic Damage +10','"Mag.Atk.Bns."+10',}},
    legs={ name="ヘルクリアトラウザ", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Mag. Acc.+4','"Mag.Atk.Bns."+15',}},
    ammo="サンカスサシェ+1",
    left_ear="ハーティーピアス",
    waist="風鳥の帯",
    neck="オルンミラトルク",
    neck="デビリスメダル",
    sub="トィエライエキュ+1",
    head="ナティラハット",
    feet={ name="ヘルクリアブーツ", augments={'Accuracy+2','"Mag.Atk.Bns."+23','Mag. Acc.+15 "Mag.Atk.Bns."+15',}},
    left_ear="マリグナスピアス",
    waist="ピュシアサッシュ+1",
    left_ring="キシャールリング",
    back={ name="カムラスマント", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    sub="ガンバンテイン",
    back={ name="インタラアスケープ", augments={'CHR+20','Accuracy+20 Attack+20','CHR+10','Weapon skill damage +10%',}},
    body={ name="ＰＤガウン+3", augments={'Enhances "Enlightenment" effect',}},
    neck="デュアルカラー+1",
    left_ear="王将の耳飾り",
    neck={ name="クレリクトルク+2", augments={'Path: A',}},
    body="ＡＺコート+1",
    back="黄昏の羽衣",
    feet={ name="ＢＩスリッパー+3", augments={'Enhances "Nightingale" effect',}},
    feet={ name="マーリンクラッコー", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Magic burst dmg.+7%','INT+13','"Mag.Atk.Bns."+5',}},
    body="アヤモコラッツァ+2",
    hands="アヤモマノポラ+2",
    ammo="プシロメン",
    range="ギャッラルホルン",
    head={ name="カイロンハット", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','"Fast Cast"+2','Mag. Acc.+15',}},
    head="ＴＥキャップ+1",
    body={ name="カイロンダブレット", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Conserve MP"+7','CHR+8','Mag. Acc.+15',}},
    legs="アヤモコッシャレ+2",
    head={ name="ケカスミトラ+1", augments={'MP+80','"Cure" spellcasting time -7%','Enmity-6',}},
    feet="ＦＬコテュルヌ+1",
    left_ring="ＷＬリング+1",
    head="アヤモツッケット+2",
    waist="エンブラサッシュ",
    left_ring="カッヤレスリング",
    hands={ name="カイロングローブ", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Enmity-1','MND+6','Mag. Acc.+15','"Mag.Atk.Bns."+4',}},
    neck="ロリケートトルク+1",
    back={ name="ゴストファイケープ", augments={'Enfb.mag. skill +5','Enha.mag. skill +10','Mag. Acc.+3','Enh. Mag. eff. dur. +18',}},
    left_ring="メリディアンリング",
    legs={ name="カイロンホーズ", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','MND+5','Mag. Acc.+12','"Mag.Atk.Bns."+3',}},
    feet={ name="カイロンスリッパー", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','INT+5','Mag. Acc.+12','"Mag.Atk.Bns."+8',}},
    hands={ name="ケカスカフス+1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    feet="アヤモガンビエラ+2",
    neck="サンクトネックレス",
    left_ear="ルガルバンダピアス",
    legs="インヤガシャルワ",
    waist="霊亀腰帯",
    waist="エスカンストーン",
    legs="インヤガシャルワ+1",
    left_ear="エンメルカルピアス",
    hands="ＴＥミトン+3",
    left_ear="テロスピアス",
    left_ear="ディグニタリピアス",
    back={ name="カンペストレケープ", augments={'Pet: M.Acc.+20 Pet: M.Dmg.+20','Pet: Haste+10',}},
    left_ring="アルコンリング",
    left_ear="怯懦の耳",
    legs="インヤガシャルワ+2",
    left_ring="ヘタイロイリング",
    back={ name="カムラスマント", augments={'"Snapshot"+10',}},
    left_ear="ヒーリングピアス",
    sub="カルンウェナン",
    left_ring="ラジャスリング",
    neck="シュルマヌカラー",
    neck="アダドアミュレット",
    range={ name="リノス", augments={'Accuracy+17','"Dbl.Atk."+3','Quadruple Attack +3',}},
    neck="リソムネックレス",
    head={ name="ヴァニヤフード", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    feet={ name="ケカスブーツ+1", augments={'Mag. Acc.+20','"Cure" potency +6%','"Fast Cast"+4',}},
    legs={ name="マーリンシャルワ", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','Magic burst dmg.+7%','INT+5','Mag. Acc.+13','"Mag.Atk.Bns."+10',}},
    feet="ブリオソスリッパー",
    back={ name="ベレナスケープ", augments={'"Snapshot"+10',}},
    head="ＢＲランドリト+3",
    left_ear="ビティフィクピアス",
    waist="ウィンバフベルト+1",
    left_ear="デディションピアス",
    left_ring="エポナリング",
    head="ＦＬキャロ+1",
    body="ＦＬオングルリヌ+1",
    back={ name="ナントセルタケープ", augments={'MP+60','Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10',}},
    hands="ＦＬマンシェト+1",
    legs={ name="ＢＩキャニオンズ+3", augments={'Enhances "Soul Voice" effect',}},
    feet="リーガルパンプス+1",
    sub={ name="カーリ", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
    back={ name="インタラアスケープ", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10',}},
    hands={ name="マーリンダスタナ", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Blood Pact Dmg.+10','Pet: DEX+3','Pet: Mag. Acc.+2',}},
    back={ name="スセロスケープ", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10',}},
    body={ name="ロゼトジャズラン+1", augments={'Path: A',}},
    range="ダウルダヴラ",
    range="マルシュアス",
    sub={ name="バルフォーク", augments={'Path: C',}},
    legs="ＦＬラングラヴ+1",
    feet={ name="ヴァニヤクロッグ", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ear="オノワイヤリング",
    left_ear="オノワイヤリング+1",
    body="ＴＥブリオー+3",
    neck="エーラペンダント",
    left_ring="メフィタスリング",
    left_ring="メフィタスリング+1",
    left_ear="カラミタスピアス",
    sub="ボレラブンガ",
    sub="デイブレイクワンド",
    waist="闇輪の帯",
    left_ring="フレキリング",
    sub={ name="ガーダ", augments={'Enh. Mag. eff. dur. +6','"Mag.Atk.Bns."+12',}},
    sub="スセレスロッド",
    sub="バドースロッド",
    sub="レテクロッド+1",
    main={ name="アーカII", augments={'Light Affinity: Magic Accuracy+6 Light Affinity: Recast time-14%','Light Affinity: Magic Damage+1',}},
    main={ name="アカデモス", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    main="トゥプシマティ",
    main="フヴェルゲルミル",
    main="レテクスタッフ+1",
    ammo="ガストリタスラム+1",
    head="マルクィシャポー+2",
    hands="レテクバングル+1",
    legs="ＡＣパンツ+1",
    neck={ name="アギュトストール+2", augments={'Path: A',}},
    neck="ベーテルペンダント",
    waist="火輪の帯",
    waist="雷輪の帯",
    waist="光輪の帯",
    left_ring="マルクィリング",
    left_ring={ name="メタモルリング+1", augments={'Path: A',}},
    head={ name="テルキネキャップ", augments={'Mag. Acc.+23','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    body={ name="テルキネシャジュブ", augments={'Mag. Acc.+24','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    hands={ name="テルキネグローブ", augments={'Mag. Acc.+22','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    legs={ name="テルキネブラコーニ", augments={'Mag. Acc.+25','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    feet={ name="テルキネピガッシュ", augments={'Mag. Acc.+24','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    head="ＡＣボード+3",
    hands="ＡＣブレーサー+3",
    legs={ name="ＰＤパンツ+3", augments={'Enhances "Tabula Rasa" effect',}},
    feet="ＡＣローファー+3",
    feet={ name="ＰＤローファー+3", augments={'Enhances "Stormsurge" effect',}},
    left_ring="ラハブリング",
    left_ring="ジャリリング",
    left_ring="ローカスリング",
    left_ring="夢神の指輪",
    sub="レリックダガー",
    sub="マグヌスソード",
    sub="ターニオンダガー+1",
    sub={ name="金糸雀", augments={'"Store TP"+4','AGI+2','Accuracy+10','Attack+18','DMG:+12',}},
    main="石切丸",
    head="ガネーシャマスク",
    ammo="佐助手裏剣",
    ammo="伊達手裏剣",
    head="ＬＴシャペル+1",
    body="ＬＴサヨン+1",
    hands="ＬＴガントロ+1",
    legs="ＬＴフュゾー+1",
    feet="ＬＴウゾー+1",
    body="ＡＴタバード+3",
    hands="ＡＴグローブ+3",
    head={ name="ＶＩシャポー+3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body={ name="ＶＩタバード+3", augments={'Enhances "Chainspell" effect',}},
    hands={ name="ＶＩグローブ+3", augments={'Enhancing Magic duration',}},
    legs={ name="ＶＩタイツ+3", augments={'Enspell Damage','Accuracy',}},
    feet={ name="ＶＩブーツ+3", augments={'Immunobreak Chance',}},
    sub="マクセンチアス",
    head="白ララブキャップ+1",
    waist="チャークベルト",
    sub="プクラトムージュ",
    sub="プクラトムージュ+1",
    sub={ name="コラーダ", augments={'Enh. Mag. eff. dur. +4','Mag. Acc.+7','"Mag.Atk.Bns."+10',}},
    range="ウルル",
    ammo="イェットシーラ+1",
    head="ＡＴシャポー+1",
    neck={ name="デュエルトルク+2", augments={'Path: A',}},
    back={ name="スセロスケープ", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%',}},
    legs="シェダルサラウィル",
    neck="ノデンズゴルゲット",
    left_ear="スノトラピアス",
    legs="ＡＴタイツ+1",
    sub="ネイグリング",
    neck="アヌートルク",
    waist="セールフィベルト+1",
    waist={ name="アキュイテベルト+1", augments={'Path: A',}},
    sub={ name="クロセアモース", augments={'Path: C',}},
    sub={ name="シブロン", augments={'TP Bonus +1000',}},
    sub={ name="ＢＦバルワク+1", augments={'Phys. dmg. taken -4%','"Shield Mastery"+3','Magic dmg. taken -4%',}},
    feet={ name="テーオンブーツ", augments={'Mag. Acc.+19','"Dual Wield"+5','DEX+10',}},
    neck="アイニアカラー",
    left_ring="シーリチリング+1",
    head="ジャリコロナル+2",
    body="ジャリローブ+2",
    hands="ジャリカフス+2",
    legs="ジャリスロップス+2",
    feet="ジャリピガッシュ+2",
    head={ name="ＦＵバンド+3", augments={'Enhances "Battuta" effect',}},
    head="ＲＮバンド+3",
    head="トゥルムキャップ+1",
    head="ハリタスヘルム",
    head="ＥＲガレア+1",
    body="ＲＮコート+3",
    body={ name="ＦＵコート+3", augments={'Enhances "Elemental Sforzo" effect',}},
    head={ name="アデマボンネット+1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body={ name="アデマジャケット+1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body="エメットハーネス+1",
    body={ name="テーオンタバード", augments={'"Fast Cast"+5','Phalanx +3',}},
    hands="メガナダグローブ+2",
    hands="トゥルムミトン+1",
    hands={ name="テーオングローブ", augments={'Phalanx +3',}},
    hands={ name="アデマリスト+1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    hands="クーリスグローブ",
    legs={ name="ＦＵトラウザ+3", augments={'Enhances "Inspire" effect',}},
    legs="メガナダショウス+2",
    legs={ name="テーオンタイツ", augments={'Phalanx +3',}},
    legs="ＥＲレグガード+1",
    feet="メガナダジャンボ+2",
    hands={ name="ローハイドグローブ", augments={'HP+50','Accuracy+15','Evasion+20',}},
    feet="ＥＲグリーヴ+1",
    neck={ name="フサルクトルク+2", augments={'Path: A',}},
    neck="月光の首飾り",
    waist="イオスケハベルト+1",
    waist="エングレイブベルト",
    back={ name="オーグマケープ", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Enmity+10','Damage taken-5%',}},
    back={ name="ディバートケープ", augments={'Enmity+4','"Embolden"+15','"Dbl.Atk."+1','Damage taken-2%',}},
    left_ring="ニックマドゥリング",
    main="エピオラトリー",
    head="マリグナスシャポー",
    body="マリグナスタバード",
    hands="マリグナスグローブ",
    legs="マリグナスタイツ",
    feet="マリグナスブーツ",
    head={ name="カマインマスク+1", augments={'Accuracy+20','Mag. Acc.+12','"Fast Cast"+4',}},
    body={ name="カマインスケイル+1", augments={'Attack+20','"Mag.Atk.Bns."+12','"Dbl.Atk."+4',}},
    hands={ name="カマインフィンガ+1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    legs={ name="カマインクウィス+1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="カマイングリーヴ+1", augments={'Accuracy+12','DEX+12','MND+20',}},
    sub="アークシールド",
    ammo="サピエンスオーブ",
    ammo="ノブキエリ",
    waist="オーシャンサッシュ",
    left_ear="アースクライピアス",
    left_ear="ブルタルピアス",
    left_ear="素破の耳",
    waist="カシリベルト",
    feet={ name="テーオンブーツ", augments={'Spell interruption rate down -10%','Phalanx +3',}},
    feet="トゥルムレギンス+1",
    neck="ストーンゴルゲット",
    waist="ギシドゥバサッシュ",
    back="月明の羽衣",
    left_ring="シーリチリング+1",
    sub="コーンスー",
    left_ring="月光の指輪",
    body={ name="サムヌーハコート", augments={'Mag. Acc.+12','"Mag.Atk.Bns."+12','"Dual Wield"+3',}},
    legs="蓐収佩楯",
    waist="オルペウスサッシュ",
    waist="フルームベルト+1",
    neck="フォシャゴルゲット",
    waist="フォシャベルト",
    left_ear="ハラサズピアス",
    left_ear="イシュヴァラピアス",
    left_ear="エアバニピアス",
    left_ear={ name="胡蝶のイヤリング", augments={'"Mag.Atk.Bns."+4','TP Bonus +250',}},
    left_ring="ゲリリング",
    left_ring="イラブラットリング",
    left_ring="ディンジルリング",
    legs={ name="ローハイドトラウザ", augments={'MP+50','"Fast Cast"+5','"Refresh"+1',}},
    ammo="ヤメラング",
    hands={ name="ＦＵミトン+1", augments={'Enhances "Sleight of Sword" effect',}},
    hands="ＲＮミトン+1",
    feet={ name="ＦＵブーツ+1", augments={'Enhances "Rayke" effect',}},
    feet="ＲＮブーツ+1",
    legs={ name="サムヌータイツ", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    waist="オドンブラサッシュ",
    sub="メンシストラップ+1",
    ammo="オゲルミルオーブ+1",
}