sets.exported={
    left_ring="Warp Ring",
    item="Voidfoot: PLD",
    item="Kindred's Crest",
    left_ear="Mache Earring +1",
    item="Alfard's Fang",
    item="H. Kindred Crest",
    item="Mog Pell (Red)",
    sub="Tauret",
    item="Wyvern Skin",
    item="Wind Cluster",
    item="Silver Thread",
    item="Storage Slip 18",
    item="Storage Slip 27",
    item="Lustreless Scale",
    item="Bale Seal: Hn.",
    item="Storage Slip 16",
    item="Orison Seal: Hn.",
    item="Linkpearl",
    sub="Aern Dagger",
    sub="Ibushi Shinai",
    left_ring="Defending Ring",
    left_ring="Dim. Ring (Dem)",
    item="Storage Slip 28",
    item="Copper Voucher",
    item="S. Kindred Crest",
    item="Light Cluster",
    item="Yggdreant Root",
    main="Bounty Sickle",
    item="Silver Voucher",
    item="Fire Cluster",
    item="Lightning Cluster",
    item="Earth Cluster",
    main="Lost Sickle",
    item="Dark Cluster",
    item="Snowslit Stone +1",
    item="Snowslit Stone +1",
    main="Aern Spear",
    item="Adaman Ingot",
    sub="Trainee Burin",
    item="Snowslit Stone +1",
    item="Gold Ingot",
    item="Mercury",
    item="Storage Slip 25",
    item="Snowslit Stone +1",
    item="Cockatrice Skin",
    main="Uchigatana",
    item="Storage Slip 23",
    sub="Kraken Club",
    main="Hapy Staff",
    item="Goblin Mushpot",
    item="Snowslit Stone +1",
    item="Earth Crystal",
    ammo="Date Shuriken",
    item="Forbidden Key",
    item="Kaginawa",
    item="Storage Slip 21",
    item="Ice Cluster",
    item="Pearlsack",
    item="Red Chip",
    item="Water Cluster",
    item="H.Q. Wivre Hide",
    item="Bu.Abjuration: Ft.",
    item="Purple Chip",
    item="Apple Pie",
    sub="Twashtar",
    item="Storage Slip 10",
    item="Shikanofuda",
    item="Gil",
    body="Pupil's Shirt",
    item="Green 9D Almirah",
    range="Fail-Not",
    item="Silberkranz",
    sub="Ihintanto",
    feet="Thatch Boots",
    body="Councilor's Garb",
    head="Ebur Hat",
    sub={ name="Tahtib", augments={'Occ. atk. 2-4 times+12',}},
    body="Vedic Coat",
    hands="Carapacho Cuffs",
    legs="Ebon Pants",
    body="Count's Garb",
    sub={ name="Nobilis", augments={'Attack+5',}},
    left_ring="Matrimony Band",
    head="Charis Tiara +1",
    item="Panetiere",
    head={ name="Hagondes Hat +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Avatar perpetuation cost" -5',}},
    back="Felicitas Cape +1",
    item="Guild Flyers",
    legs="Pupil's Trousers",
    body="Ebur Coat",
    head="Midras's Helm +1",
    back={ name="Rudianos's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    range="Yoichinoyumi",
    body={ name="Hagondes Coat +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','Pet: Mag. Acc.+24',}},
    item="San. Marriage Cert.",
    left_ring="Fenian Ring",
    body="Wedding Dress",
    head="Straw Hat",
    body="Anhur Robe",
    body="Pupil's Camisa",
    body="Goetia Coat +2",
    item="Orchestrion",
    main="Mage's Staff",
    body="Blessed Bliaut",
    back="Nexus Cape",
    left_ear="Neritic Earring",
    body="Culinarian's Smock",
    body="Noble's Tunic",
    feet="Hippomenes Socks",
    hands="Ebur Cuffs",
    hands="Argute Bracers +2",
    feet="Wedding Boots",
    feet="Dream Boots +1",
    legs={ name="Gende. Spats +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -3%','"Cure" spellcasting time -5%',}},
    hands="Culinarian's Cuffs",
    item="Martial Ball Invite",
    hands="Work Gloves",
    hands="Noble's Mitts",
    range={ name="Sparrowhawk +2", augments={'TP Bonus +1000',}},
    sub="Leafkin Shield",
    legs="Wedding Hose",
    hands="Councilor's Cuffs",
    legs="Perdition Slops",
    back="Reiki Cloak",
    feet="Naga Kyahan",
    left_ear="Hirudinea Earring",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +6','Enha.mag. skill +9','Mag. Acc.+9','Enh. Mag. eff. dur. +19',}},
    head="Ebon Hat",
    item="Green Chip",
    head="Ebur Caubeen",
    item="Weavers' Stall",
    item="Vana'clock",
    feet="Ebur Sabots",
    item="H♀ Mannequin",
    left_ear="Gelai Earring",
    item="Culinary Stall",
    item="Galley Kitchen",
    item="Alzadaal Table",
    hands="Ebon Gages",
    legs={ name="Taeon Tights", augments={'Accuracy+20 Attack+20','"Triple Atk."+2','DEX+10',}},
    sub="Excalipoor",
    waist="Witful Belt",
    head={ name="Herculean Helm", augments={'Rng.Acc.+24 Rng.Atk.+24','Crit.hit rate+4','STR+3','Rng.Acc.+12','Rng.Atk.+7',}},
    hands="Commodore Gants",
    legs="White Slacks",
    item="Kupon I-Seal",
    head="Lilac Corsage",
    body={ name="Gende. Bliaut +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    body="Chelona Blazer",
    body="Pup. Tobe",
    item="Cehuetzi Pelt",
    sub="Aegis",
    main="Beorc Sword",
    item="Kukulkan's Skin",
    hands="Pup. Dastanas",
    item="Wyrdweave",
    item="S. Astral Detritus",
    legs="Femina Subligar",
    item="Eschite Ore",
    item="Defiant Scarf",
    item="Rusted I. Card",
    item="Rusted I. Card",
    feet="Pup. Babouches",
    item="Kukulkan's Skin",
    sub="Zuuxowu Grip",
    item="Defiant Scarf",
    feet={ name="Gende. Galosh. +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -3%','"Cure" spellcasting time -5%',}},
    head={ name="Gende. Caubeen +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    body={ name="Weather. Robe +1", augments={'MP+120',}},
    item="Befouled Silver",
    main={ name="Keraunos", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Elemental Siphon"+25','INT+21',}},
    sub="Izcalli",
    item="Hepatizon Ingot",
    item="Hades' Claw",
    sub="Charm Wand",
    item="Sif's Macrame",
    sub="Miracle Wand",
    item="Bztavian Wing",
    item="S. Astral Detritus",
    item="Beastmen's Medal",
    body="Heart Apron +1",
    hands={ name="Adhemar Wrist. +1", augments={'AGI+12','Rng.Acc.+20','Rng.Atk.+20',}},
    body="Sylvie Unity Shirt",
    head="Rawhide Mask",
    sub="Niobid Strap",
    feet="Inspirited Boots",
    range="Animator P II",
    item="Raaz Leather",
    sub="Raphael's Rod",
    back="Lupine Cape",
    item="Penelope's Cloth",
    left_ear="Novia Earring",
    left_ear="Thureous Earring",
    legs="Dashing Subligar",
    item="Vulcanite Ore",
    neck="Eidolon Pendant +1",
    ammo="Hydrocera",
    left_ear="Hermetic Earring",
    item="Sif's Lock",
    item="Akvan's Pennon",
    sub="Ochain",
    item="Plovid Effluvium",
    neck="Eddy Necklace",
    item="Eschalixir +2",
    ammo="Elis Tome",
    waist="Tempus Fugit",
    item="Forgotten Touch",
    item="Sovereign's Hide",
    left_ear="Rimeice Earring",
    waist="Oneiros Rope",
    left_ring="Apate Ring",
    back={ name="Gunslinger's Cape", augments={'Enmity-4','"Mag.Atk.Bns."+1','"Phantom Roll" ability delay -5','Weapon skill damage +1%',}},
    left_ring="Vengeful Ring",
    item="Black. I. Card",
    item="Abdhaljs Dye",
    item="Macuil Plating",
    item="Plovid Effluvium",
    item="Macuil Horn",
    item="Yggdreant Root",
    item="Defiant Scarf",
    item="Hades' Claw",
    item="Bztavian Stinger",
    item="Abdhaljs Thread",
    item="Storage Slip 09",
    item="Heavy Metal",
    item="Abdhaljs Sap",
    item="Storage Slip 01",
    item="Abdhaljs Dust",
    item="Waktza Crest",
    item="Storage Slip 03",
    item="Pil's Tuille",
    item="Abdhaljs Resin",
    item="Umbral Marrow",
    item="Muculent Ingot",
    item="A. Vou.: Feet +1",
    item="Abdhaljs Nugget",
    item="A. Tok.: Fingers",
    item="Abdhaljs Resin",
    item="Rockfin Fin",
    item="Nethercant Chain",
    item="Abdhaljs Sap",
    item="A. Vou.: Head +1",
    item="Ake-Ome Spirit",
    item="Rusted I. Card",
    item="Abdhaljs Gem",
    item="Abdhaljs Resin",
    item="A. Vou.: Fingers",
    item="A. Tok.: Feet +1",
    item="Abdhaljs Metal",
    main={ name="Ohtas", augments={'Accuracy+70','Pet: Accuracy+70','Pet: Haste+10%',}},
    item="Eschalixir +2",
    head={ name="Chironic Hat", augments={'Rng.Atk.+24','Mag. Acc.+22 "Mag.Atk.Bns."+22','"Refresh"+2','Accuracy+8 Attack+8',}},
    range="Animator P +1",
    item="Abdhaljs Fiber",
    item="Tartarian Chain",
    item="Abdhaljs Anima",
    item="Rockfin Tooth",
    item="Abdhaljs Matter",
    hands="Chironic Gloves",
    item="A. Tok.: Legs +1",
    item="A. Voucher: Back",
    ammo="Automat. Oil +3",
    item="Mog Pell (Silver)",
    item="D. Frame: Cloth.",
    item="A. Vou.: Hands +1",
    item="Abdhaljs Needle",
    item="Dark Matter",
    item="A. Voucher: Weapon",
    item="Eschalixir +2",
    item="A. Vou.: Body +1",
    item="Mog Pell (Red)",
    item="A. Tok.: Hands +1",
    item="A. Tok.: Head +1",
    sub="Paper Knife",
    item="Infinity Core",
    item="Carabosse's Gem",
    item="Cehuetzi Claw",
    sub="Malignance Sword",
    item="Tr.Abjuration: Lg.",
    item="Ruthenium Ore",
    legs="Bone Subligar",
    item="Abdhaljs Dye",
    main="Tzee Xicu's Blade",
    item="Guatambu Log",
    item="Abdhaljs Dust",
    waist="Moonbow Belt +1",
    item="Sanctity Grimoire",
    item="Yggdreant Bole",
    back={ name="Visucius's Mantle", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20','Pet: Haste+10',}},
    item="Kei's Scale",
    item="P. SCH Card",
    item="S. Astral Detritus",
    item="Vile Elixir +1",
    item="Frayed Sack (Fer)",
    item="Sublime Sushi",
    item="P. BRD Card",
    item="Bukhis's Wing",
    item="P. SMN Card",
    item="Kyou's Scale",
    item="Panacea",
    item="Storage Slip 22",
    item="Antacid",
    item="Frayed Sack (Tau)",
    item="Panacea",
    item="Fu's Scale",
    feet="Mou. Crackows +1",
    item="P. GEO Card",
    item="Panacea",
    item="Icarus Wing",
    item="Antidote",
    item="Coalition Ether",
    item="Coalition Ether",
    item="Dial Key #Ab",
    item="Abdhaljs Seal",
    item="Frayed Sack (Tau)",
    item="Storage Slip 13",
    item="Prism Powder",
    item="Gin's Scale",
    item="Maze Tabula M01",
    item="SP Gobbie Key",
    item="Instant Warp",
    item="Coconut Rusk",
    item="Carbonara",
    item="Marine Stewpot",
    item="Akamochi",
    item="Hi-Elixir",
    item="P. COR Card",
    item="Prism Powder",
    item="Miso Ramen",
    item="Storage Slip 11",
    item="Remedy",
    item="Toolbag (Kagi)",
    item="Dark Cluster",
    item="P. WHM Card",
    item="Sublime Sushi",
    item="Vile Elixir",
    item="Red Curry Bun",
    item="Coalition Ether",
    item="Frayed Sack (Tau)",
    item="Storage Slip 04",
    item="Silent Oil",
    item="Frayed Sack (Tau)",
    item="Mog Pell (Red)",
    item="Tropical Crepe",
    item="Frayed Sack (Tau)",
    item="Storage Slip 19",
    item="Vermillion's Wing",
    item="Coalition Ether",
    item="Remedy",
    item="Shiromochi",
    item="Seafood Stewpot",
    item="Toolbag (Shika)",
    item="Miso Ramen +1",
    item="Coalition Ether",
    item="Coalition Ether",
    item="P. RUN Card",
    item="Kitron Macaron",
    item="Remedy",
    item="Coalition Ether",
    item="Storage Slip 06",
    ammo="Hauksbok Arrow",
    item="Tropical Crepe",
    item="P. RDM Card",
    item="Holy Water",
    sub={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+8','"Fast Cast"+5',}},
    feet={ name="Herculean Boots", augments={'STR+3','"Mag.Atk.Bns."+25','Accuracy+14 Attack+14','Mag. Acc.+16 "Mag.Atk.Bns."+16',}},
    neck="Sacro Gorget",
    item="Holy Water",
    sub="Perun +1",
    neck="Iskur Gorget",
    item="Toolbag (Shihe)",
    sub={ name="Rostam", augments={'Path: C',}},
    legs={ name="Herculean Trousers", augments={'Pet: STR+2','"Occult Acumen"+3','"Treasure Hunter"+2','Accuracy+19 Attack+19',}},
    legs="Zoar Subligar +1",
    body="Reiki Osode",
    body={ name="Herculean Vest", augments={'Enmity+1','Accuracy+2 Attack+2','Phalanx +3','Mag. Acc.+10 "Mag.Atk.Bns."+10',}},
    range="Fomalhaut",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    range="Gastraphetes",
    range={ name="Anarchy +2", augments={'Delay:+60','TP Bonus +1000',}},
    range="Armageddon",
    ammo="Chrono Arrow",
    head="Oshosi Mask +1",
    head={ name="Taeon Chapeau", augments={'"Snapshot"+5','"Snapshot"+5',}},
    range="Annihilator",
    body="Oshosi Vest +1",
    hands="Oshosi Gloves +1",
    hands={ name="Taeon Gloves", augments={'"Mag.Atk.Bns."+18','"Snapshot"+5','"Snapshot"+5',}},
    legs={ name="Taeon Tights", augments={'"Mag.Atk.Bns."+19','"Snapshot"+5','"Snapshot"+4',}},
    legs="Osh. Trousers +1",
    ammo="Living Bullet",
    range="Gandiva",
    feet="Osh. Leggings +1",
    waist="Yemaya Belt",
    waist="Impulse Belt",
    feet="Skd. Jambeaux +1",
    item="Fire Crystal",
    waist="Refoccilation Stone",
    back={ name="Alaunus's Cape", augments={'MP+60','Eva.+20 /Mag. Eva.+20','"Fast Cast"+10',}},
    item="Orange Juice",
    item="Venus Orb",
    sub="Ark Shield",
    body="Passion Jacket",
    back="Impassive Mantle",
    feet={ name="Taeon Boots", augments={'"Mag.Atk.Bns."+19','"Snapshot"+5','"Snapshot"+5',}},
    range="Death Penalty",
    back={ name="Belenus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','"Store TP"+10',}},
    left_ring="Airy Ring",
    waist="Grunfeld Rope",
    left_ring="Dim. Ring (Holla)",
    neck={ name="Comm. Charm +2", augments={'Path: A',}},
    sub="Nusku Shield",
    left_ear="Mache Earring +1",
    left_ring="Luzaf's Ring",
    neck="Regal Necklace",
    legs={ name="Adhemar Kecks +1", augments={'AGI+12','"Rapid Shot"+13','Enmity-6',}},
    back={ name="Camulus's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
    left_ring="Emporox's Ring",
    sub="Tishtrya",
    sub="Plaiter's Shield",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+50%','MP+17','Mag. Acc.+1','DEF+4',}},
    item="Worn Sack (SD+1)",
    main={ name="Lathi", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    head="Magnifying Specs.",
    sub={ name="Taming Sari", augments={'STR+10','DEX+10','DMG:+15','"Treasure Hunter"+1',}},
    range="Aureole",
    item="Giant Femur",
    body="Weaver's Apron",
    item="Bat Wing",
    item="Revival Root",
    item="E.Abjuration: Hn.",
    item="M.Abjuration: Lg.",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
    hands={ name="Plun. Armlets +1", augments={'Enhances "Perfect Dodge" effect',}},
    item="N.Abjuration: Hn.",
    item="T. Whiteshell",
    item="Lancewood Log",
    left_ring="Craftmaster's Ring",
    item="Relic Iron",
    item="Colossal Skull",
    feet={ name="Herculean Boots", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Crit. hit damage +1%','INT+2','Mag. Acc.+4','"Mag.Atk.Bns."+13',}},
    left_ring="Endorsement Ring",
    sub="Sandung",
    neck="Smn. Collar +2",
    left_ring="Artificer's Ring",
    neck={ name="Src. Stole +2", augments={'Path: A',}},
    sub={ name="Mjollnir", augments={'DMG:+8',}},
    left_ring="Trizek Ring",
    hands={ name="Piety Mitts +3", augments={'Enhances "Martyr" effect',}},
    feet="Raid. Poulaines +2",
    feet={ name="Piety Duckbills +3", augments={'Enhances "Afflatus Solace" effect',}},
    neck="Weaver's Torque",
    left_ring="Tailor's Ring",
    head="Baayami Hat",
    body="Baayami Robe",
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+18 "Mag.Atk.Bns."+18','Magic burst dmg.+9%','MND+8','Mag. Acc.+8','"Mag.Atk.Bns."+13',}},
    neck={ name="Bard's Charm +2", augments={'Path: A',}},
    hands="Baayami Cuffs",
    legs="Baayami Slops",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst dmg.+10%','INT+10',}},
    feet="Baayami Sabots",
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Conserve MP"+4','Mag. Acc.+14','"Mag.Atk.Bns."+15',}},
    waist="Regal Belt",
    waist="Austerity Belt +1",
    left_ring="Dim. Ring (Mea)",
    hands="Regal Gloves",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','"Fast Cast"+10',}},
    main={ name="Grioavolr", augments={'Magic burst dmg.+4%','INT+19','Mag. Acc.+20','"Mag.Atk.Bns."+24',}},
    sub="Yagrush",
    head={ name="Telchine Cap", augments={'Mag. Evasion+23','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    sub={ name="Tamaxchi", augments={'Occ. atk. twice+8','Enmity-10',}},
    feet="Azimuth Gaiters +1",
    head="Mousai Turban +1",
    back={ name="Intarabus's Cape", augments={'Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Mag. crit. hit dmg. +4%','INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+15',}},
    head="Pixie Hairpin +1",
    body="Vrikodara Jupon",
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','Rng.Acc.+10','"Store TP"+10',}},
    body="Geo. Tunic +1",
    legs={ name="Gende. Spats +1", augments={'Phys. dmg. taken -4%','Song spellcasting time -5%',}},
    body="Pinga Tunic +1",
    head="Tali'ah Turban +2",
    legs="Ea Slops +1",
    back={ name="Camulus's Mantle", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','AGI+10','Weapon skill damage +10%',}},
    body={ name="Telchine Chas.", augments={'Mag. Evasion+25','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    body="Mou. Manteel +1",
    hands="Azimuth Gloves +1",
    hands="Geo. Mitaines +3",
    hands={ name="Telchine Gloves", augments={'Mag. Evasion+23','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    hands="Mousai Gages +1",
    body="Tali'ah Manteel +2",
    ammo="Incantor Stone",
    legs="Pinga Pants +1",
    feet="Geo. Sandals +1",
    head={ name="Amalric Coif +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body="Ea Houppe. +1",
    ammo="Savant's Treatise",
    legs={ name="Amalric Slops +1", augments={'INT+12','Elem. magic skill +20','Dark magic skill +20',}},
    body="Twilight Cloak",
    legs={ name="Bagua Pants +1", augments={'Enhances "Mending Halation" effect',}},
    legs={ name="Telchine Braconi", augments={'Mag. Evasion+25','Pet: "Regen"+3','Pet: Damage taken -4%',}},
    legs="Geomancy Pants +3",
    sub="Idris",
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Occult Acumen"+9','INT+14','Mag. Acc.+11','"Mag.Atk.Bns."+12',}},
    neck="Voltsurge Torque",
    feet={ name="Telchine Pigaches", augments={'Mag. Evasion+24','Pet: "Regen"+3','Pet: Damage taken -3%',}},
    left_ear="Sanare Earring",
    left_ear="Barkaro. Earring",
    body={ name="Bagua Tunic +1", augments={'Enhances "Bolster" effect',}},
    feet={ name="Amalric Nails +1", augments={'MP+80','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    head="Ea Hat +1",
    legs="Tali'ah Sera. +2",
    waist="Channeler's Stone",
    feet="Theo. Duckbills +3",
    head={ name="Vanya Hood", augments={'MP+50','"Fast Cast"+10','Haste+2%',}},
    head="Befouled Crown",
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    left_ear="Cessance Earring",
    legs="Mou. Seraweels +1",
    waist="Siegel Sash",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +10','Indi. eff. dur. +14','Pet: Damage taken -3%','Damage taken-3%',}},
    back={ name="Conveyance Cape", augments={'Summoning magic skill +5','Pet: Enmity+14','Blood Pact ab. del. II -3',}},
    left_ear="Friomisi Earring",
    sub="Clerisy Strap +1",
    neck={ name="Scout's Gorget +2", augments={'Path: A',}},
    feet="Tali'ah Crackows +2",
    head="Azimuth Hood +1",
    hands={ name="Amalric Gages +1", augments={'INT+12','Mag. Acc.+20','"Mag.Atk.Bns."+20',}},
    body={ name="Amalric Doublet +1", augments={'MP+80','"Mag.Atk.Bns."+25','"Fast Cast"+4',}},
    hands="Tali'ah Gages +2",
    body={ name="Vanya Robe", augments={'MND+10','Spell interruption rate down +15%','"Conserve MP"+6',}},
    feet={ name="Chironic Slippers", augments={'Pet: Mag. Acc.+29','Accuracy+25','"Refresh"+2','Mag. Acc.+20 "Mag.Atk.Bns."+20',}},
    hands={ name="Chironic Gloves", augments={'DEX+4','Phys. dmg. taken -2%','"Refresh"+2','Mag. Acc.+10 "Mag.Atk.Bns."+10',}},
    feet={ name="Vanya Clogs", augments={'"Cure" potency +5%','"Cure" spellcasting time -15%','"Conserve MP"+6',}},
    back={ name="Alaunus's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10',}},
    back="Swith Cape +1",
    feet={ name="Bagua Sandals +3", augments={'Enhances "Radial Arcana" effect',}},
    item="Storage Slip 12",
    sub="Kustawi +1",
    sub="Tanmogayi +1",
    item="Byakko Scrap",
    item="Ym. Gr. Coffer",
    item="Ig. Gr. Coffer",
    item="Du. Gr. Coffer",
    item="Tr. Gr. Coffer.",
    main="Hoe",
    legs="Custom Pants",
    item="Li. Gr. Coffer",
    back="Nantosuelta's Cape",
    body={ name="Pursuer's Doublet", augments={'DEX+7','AGI+10','"Recycle"+15',}},
    legs="Menhit Slacks",
    sub={ name="Vampirism", augments={'STR+10','INT+10','"Occult Acumen"+10','DMG:+15',}},
    back={ name="Rosmerta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    legs="Calmecac Subligar",
    head={ name="Herculean Helm", augments={'Rng.Acc.+25 Rng.Atk.+25','Weapon skill damage +2%','STR+14','Rng.Atk.+2',}},
    range="Killer Bow",
    body="Ebur Bliaut",
    hands="Orvail Cuffs",
    hands="Ebur Gloves",
    item="Storage Slip 15",
    body={ name="Pitre Tobe +1", augments={'Enhances "Overdrive" effect',}},
    feet={ name="Taeon Boots", augments={'Spell interruption rate down -10%',}},
    hands="Blksmith. Cuffs",
    left_ear="Savant's Earring",
    body={ name="Witching Robe", augments={'MP+50','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Refresh"+1',}},
    item="Storage Slip 08",
    hands="Ayao's Gages",
    item="Storage Slip 17",
    range="Compensator",
    head="Bridal Corsage",
    body="Jody Shirt",
    sub={ name="Solstice", augments={'Mag. Acc.+20','Pet: Damage taken -4%','"Fast Cast"+5',}},
    feet="Ebur Boots",
    main="Trial Blade",
    sub={ name="Sindri", augments={'Accuracy+50','Attack+30','"Dbl.Atk."+5',}},
    head="Haruspex Hat +1",
    left_ear="Novio Earring",
    left_ring="Garuda Ring +1",
    item="Gr. Gr. Coffer",
    body="Mummu Jacket +1",
    hands="Custom F Gloves",
    body="Aketon",
    main="Malignance Pole",
    ammo="Ginsen",
    body="Mandragora Shirt",
    sub="Mercurial Kris",
    body="Cossie Top +1",
    item="Storage Slip 20",
    feet="Thur. Boots +1",
    item="Storage Slip 14",
    left_ear="Signal Pearl",
    neck="Jokushu Chain",
    feet="Chelona Boots +1",
    left_ear="Enervating Earring",
    item="Dream Coffer",
    left_ring="Cacoethic Ring",
    left_ear="Genmei Earring",
    body="Woodland Tunic",
    left_ring="Patricius Ring",
    sub="Excalibur",
    item="Storage Slip 02",
    sub="Genmei Shield",
    legs="Woodland Pants",
    back="Tempered Cape +1",
    feet="Woodland Boots",
    sub="Vorpal Sword",
    neck="Chocobo Whistle",
    feet="Pursuer's Gaiters",
    body="Seidr Cotehardie",
    body="Shango Robe",
    feet="Serpentes Sabots",
    feet="Orvail Souliers",
    main={ name="Aettir", augments={'Accuracy+70','Mag. Evasion+50','Weapon skill damage +10%',}},
    left_ring="Echad Ring",
    main={ name="Espiritus", augments={'Summoning magic skill +15','Pet: Mag. Acc.+30','Pet: Damage taken -4%',}},
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Mag. Acc.+10','"Dual Wield"+10',}},
    head={ name="Merlinic Hood", augments={'Pet: Mag. Acc.+24 Pet: "Mag.Atk.Bns."+24','Blood Pact Dmg.+9','Pet: Mag. Acc.+7',}},
    head="Con. Horn +1",
    body={ name="Merlinic Jubbah", augments={'Pet: Mag. Acc.+24 Pet: "Mag.Atk.Bns."+24','Blood Pact Dmg.+10','Pet: STR+3',}},
    body={ name="Glyphic Doublet +1", augments={'Reduces Sp. "Blood Pact" MP cost',}},
    body="Con. Doublet +3",
    hands={ name="Glyphic Bracers +1", augments={'Inc. Sp. "Blood Pact" magic burst dmg.',}},
    hands="Lamassu Mitts +1",
    legs={ name="Glyphic Spats +1", augments={'Increases Sp. "Blood Pact" accuracy',}},
    legs={ name="Apogee Slacks +1", augments={'Pet: STR+20','Blood Pact Dmg.+14','Pet: "Dbl. Atk."+4',}},
    legs="Beck. Spats +1",
    head={ name="Piety Cap +3", augments={'Enhances "Devotion" effect',}},
    feet={ name="Glyph. Pigaches +1", augments={'Inc. Sp. "Blood Pact" magic crit. dmg.',}},
    head={ name="Apogee Crown +1", augments={'MP+80','Pet: Attack+35','Blood Pact Dmg.+8',}},
    waist="Incarnation Sash",
    back={ name="Conveyance Cape", augments={'Summoning magic skill +3','Pet: Enmity+7','Blood Pact Dmg.+4',}},
    left_ear="Esper Earring",
    left_ring="Fervor Ring",
    head={ name="Glyphic Horn +1", augments={'Enhances "Astral Flow" effect',}},
    body="Beck. Doublet +1",
    hands="Asteria Mitts +1",
    main={ name="Grioavolr", augments={'Blood Pact Dmg.+7','Pet: INT+9','Pet: Mag. Acc.+20','Pet: "Mag.Atk.Bns."+25',}},
    legs="Assid. Pants +1",
    feet="Beck. Pigaches +1",
    body="Brioso Justau. +3",
    waist="Lucidity Sash",
    left_ear="Evans Earring",
    left_ring="Evoker's Ring",
    main="Nirvana",
    head={ name="Bihu Roundlet +3", augments={'Enhances "Con Anima" effect',}},
    sub="Vox Grip",
    left_ear="Gelos Earring",
    neck="Caller's Pendant",
    feet={ name="Apogee Pumps +1", augments={'MP+80','Pet: Attack+35','Blood Pact Dmg.+8',}},
    hands={ name="Merlinic Dastanas", augments={'Pet: Mag. Acc.+25 Pet: "Mag.Atk.Bns."+25','Blood Pact Dmg.+8','Pet: DEX+7','Pet: "Mag.Atk.Bns."+10',}},
    body={ name="Piety Bliaut +3", augments={'Enhances "Benediction" effect',}},
    left_ear="Smn. Earring",
    hands={ name="Gende. Gages +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -4%','"Cure" spellcasting time -4%',}},
    back={ name="Belenus's Cape", augments={'AGI+20','Mag. Acc+20 /Mag. Dmg.+20','Weapon skill damage +10%',}},
    sub="Enki Strap",
    head={ name="Telchine Cap", augments={'"Elemental Siphon"+35',}},
    sub="Elan Strap +1",
    hands={ name="Bihu Cuffs +3", augments={'Enhances "Con Brio" effect',}},
    back={ name="Alaunus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10',}},
    legs={ name="Lengo Pants", augments={'INT+5','Mag. Acc.+4','"Mag.Atk.Bns."+1','"Refresh"+1',}},
    hands="Brioso Cuffs +3",
    legs="Th. Pant. +3",
    body={ name="Telchine Chas.", augments={'"Elemental Siphon"+30',}},
    hands={ name="Telchine Gloves", augments={'"Elemental Siphon"+30',}},
    neck="Mizu. Kubikazari",
    back={ name="Camulus's Mantle", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','"Store TP"+10',}},
    feet="Convo. Pigaches +3",
    left_ring="Varar Ring +1",
    waist="Shinjutsu-no-Obi +1",
    waist="Luminary Sash",
    waist="Acerbic Sash +1",
    waist="Isa Belt",
    waist="Rumination Sash",
    waist="Olympus Sash",
    waist="Casso Sash",
    waist="Ninurta's Sash",
    waist="Hachirin-no-Obi",
    left_ring="Stikini Ring +1",
    legs={ name="Telchine Braconi", augments={'"Elemental Siphon"+35',}},
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+15 Pet: Rng. Acc.+15','Pet: Mag. Acc.+15','Pet: Damage taken -5%',}},
    head="Ebers Cap +1",
    feet="Brioso Slippers +3",
    body="Ebers Bliaut +1",
    hands="Ebers Mitts +1",
    legs={ name="Piety Pantaln. +3", augments={'Enhances "Afflatus Misery" effect',}},
    range={ name="Linos", augments={'Accuracy+15','Weapon skill damage +3%','Quadruple Attack +3',}},
    legs="Ebers Pant. +1",
    feet="Ebers Duckbills +1",
    head="Beckoner's Horn +1",
    body={ name="Apo. Dalmatica +1", augments={'Summoning magic skill +20','Enmity-6','Pet: Damage taken -4%',}},
    body={ name="Bihu Jstcorps. +3", augments={'Enhances "Troubadour" effect',}},
    feet={ name="Merlinic Crackows", augments={'Pet: Mag. Acc.+19 Pet: "Mag.Atk.Bns."+19','Blood Pact Dmg.+10','Pet: AGI+9','Pet: Mag. Acc.+10',}},
    sub={ name="Queller Rod", augments={'MP+80','"Cure" potency +15%','Enmity-5',}},
    back={ name="Rhapsode's Cape", augments={'HP+29','Mag. Acc.+5','Enmity-6',}},
    sub="Beneficus",
    main={ name="Arka I", augments={'Light Affinity: Magic Accuracy+1','Light Affinity: Magic Damage+6 Light Affinity: Casting time-14%',}},
    back={ name="Ogma's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Weapon skill damage +10%',}},
    ammo="Esper Stone +1",
    ammo="Hasty Pinion +1",
    ammo="Homiliary",
    ammo="Pemphredo Tathlum",
    head="Inyanga Tiara +2",
    sub="Culminus",
    sub={ name="Genbu's Shield", augments={'"Cure" potency +5%','"Cure" spellcasting time -6%','MP+27',}},
    neck="Mnbw. Whistle +1",
    sub={ name="Asclepius", augments={'Path: C',}},
    hands={ name="Fanatic Gloves", augments={'MP+50','Healing magic skill +10','"Conserve MP"+7','"Fast Cast"+7',}},
    body={ name="Kaykaus Bliaut +1", augments={'MP+80','"Cure" potency +6%','"Conserve MP"+7',}},
    hands="Dynasty Mitts",
    waist="Skrymir Cord +1",
    left_ring="Ramuh Ring +1",
    sub="Ammurapi Shield",
    feet="Herald's Gaiters",
    range={ name="Linos", augments={'Accuracy+15','"Fast Cast"+4','AGI+6',}},
    legs={ name="Kaykaus Tights +1", augments={'MP+80','"Cure" spellcasting time -7%','Enmity-6',}},
    neck="Incanter's Torque",
    body={ name="Herculean Vest", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Enmity-3','AGI+3','Mag. Acc.+5','"Mag.Atk.Bns."+12',}},
    back="Solemnity Cape",
    back={ name="Nantosuelta's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','"Mag.Atk.Bns."+10',}},
    range="Blurred Harp +1",
    back={ name="Mending Cape", augments={'Healing magic skill +10','Enha.mag. skill +8','Mag. Acc.+8',}},
    ammo="Staunch Tathlum +1",
    left_ear="Mendi. Earring",
    left_ear="Etiolation Earring",
    left_ear="Glorious Earring",
    neck={ name="Bagua Charm +2", augments={'Path: A',}},
    left_ear="Enchntr. Earring +1",
    left_ear="Andoaa Earring",
    back="Fi Follet Cape +1",
    left_ring="Varar Ring +1",
    left_ear="Loquac. Earring",
    waist="Bishop's Sash",
    left_ear="Mimir Earring",
    left_ring="Shiva Ring +1",
    left_ring="Shiva Ring +1",
    waist="Kobo Obi",
    back={ name="Campestres's Cape", augments={'Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20',}},
    left_ring="Menelaus's Ring",
    left_ring="Haoma's Ring",
    left_ring="Prolix Ring",
    hands="Inyan. Dastanas +2",
    left_ring="Stikini Ring +1",
    head={ name="Herculean Helm", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Crit. hit damage +1%','STR+8','Mag. Acc.+7','"Mag.Atk.Bns."+14',}},
    ammo="Regal Gem",
    body="Inyanga Jubbah +2",
    feet="Inyan. Crackows +2",
    back={ name="Belenus's Cape", augments={'AGI+20','Rng.Acc.+20 Rng.Atk.+20','AGI+10','Weapon skill damage +10%',}},
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Mag. Acc.+4','"Mag.Atk.Bns."+15',}},
    ammo="Sancus Sachet +1",
    left_ear="Hearty Earring",
    waist="Fucho-no-Obi",
    neck="Orunmila's Torque",
    neck="Debilis Medallion",
    sub="Thuellaic Ecu +1",
    head="Nahtirah Hat",
    feet={ name="Herculean Boots", augments={'Accuracy+2','"Mag.Atk.Bns."+23','Mag. Acc.+15 "Mag.Atk.Bns."+15',}},
    left_ear="Malignance Earring",
    waist="Pythia Sash +1",
    left_ring="Kishar Ring",
    back={ name="Camulus's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
    sub="Gambanteinn",
    back={ name="Intarabus's Cape", augments={'CHR+20','Accuracy+20 Attack+20','CHR+10','Weapon skill damage +10%',}},
    neck="Dualism Collar +1",
    left_ear="Regal Earring",
    neck={ name="Clr. Torque +2", augments={'Path: A',}},
    body="Azimuth Coat +1",
    back="Twilight Cape",
    feet={ name="Bihu Slippers +3", augments={'Enhances "Nightingale" effect',}},
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Magic burst dmg.+7%','INT+13','"Mag.Atk.Bns."+5',}},
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +2",
    ammo="Psilomene",
    range="Gjallarhorn",
    head={ name="Chironic Hat", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','"Fast Cast"+2','Mag. Acc.+15',}},
    head="Theo. Cap +1",
    body={ name="Chironic Doublet", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','"Conserve MP"+7','CHR+8','Mag. Acc.+15',}},
    legs="Aya. Cosciales +2",
    head={ name="Kaykaus Mitra +1", augments={'MP+80','"Cure" spellcasting time -7%','Enmity-6',}},
    feet="Fili Cothurnes +1",
    left_ring="Woltaris Ring +1",
    head="Aya. Zucchetto +2",
    waist="Embla Sash",
    left_ring="K'ayres Ring",
    hands={ name="Chironic Gloves", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Enmity-1','MND+6','Mag. Acc.+15','"Mag.Atk.Bns."+4',}},
    neck="Loricate Torque +1",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +5','Enha.mag. skill +10','Mag. Acc.+3','Enh. Mag. eff. dur. +18',}},
    left_ring="Meridian Ring",
    legs={ name="Chironic Hose", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','MND+5','Mag. Acc.+12','"Mag.Atk.Bns."+3',}},
    feet={ name="Chironic Slippers", augments={'Mag. Acc.+24 "Mag.Atk.Bns."+24','INT+5','Mag. Acc.+12','"Mag.Atk.Bns."+8',}},
    hands={ name="Kaykaus Cuffs +1", augments={'MP+80','MND+12','Mag. Acc.+20',}},
    feet="Aya. Gambieras +2",
    neck="Sanctity Necklace",
    left_ear="Lugalbanda Earring",
    legs="Inyanga Shalwar",
    waist="Reiki Yotai",
    waist="Eschan Stone",
    legs="Inyanga Shalwar +1",
    left_ear="Enmerkar Earring",
    hands="Theophany Mitts +3",
    left_ear="Telos Earring",
    left_ear="Digni. Earring",
    back={ name="Campestres's Cape", augments={'Pet: M.Acc.+20 Pet: M.Dmg.+20','Pet: Haste+10',}},
    left_ring="Archon Ring",
    left_ear="Crematio Earring",
    legs="Inyanga Shalwar +2",
    left_ring="Hetairoi Ring",
    back={ name="Camulus's Mantle", augments={'"Snapshot"+10',}},
    left_ear="Healing Earring",
    sub="Carnwenhan",
    left_ring="Rajas Ring",
    neck="Shulmanu Collar",
    neck="Adad Amulet",
    range={ name="Linos", augments={'Accuracy+17','"Dbl.Atk."+3','Quadruple Attack +3',}},
    neck="Lissome Necklace",
    head={ name="Vanya Hood", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    feet={ name="Kaykaus Boots +1", augments={'Mag. Acc.+20','"Cure" potency +6%','"Fast Cast"+4',}},
    legs={ name="Merlinic Shalwar", augments={'Mag. Acc.+21 "Mag.Atk.Bns."+21','Magic burst dmg.+7%','INT+5','Mag. Acc.+13','"Mag.Atk.Bns."+10',}},
    feet="Brioso Slippers",
    back={ name="Belenus's Cape", augments={'"Snapshot"+10',}},
    head="Brioso Roundlet +3",
    left_ear="Beatific Earring",
    waist="Windbuffet Belt +1",
    left_ear="Dedition Earring",
    left_ring="Epona's Ring",
    head="Fili Calot +1",
    body="Fili Hongreline +1",
    back={ name="Nantosuelta's Cape", augments={'MP+60','Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10',}},
    hands="Fili Manchettes +1",
    legs={ name="Bihu Cannions +3", augments={'Enhances "Soul Voice" effect',}},
    feet="Regal Pumps +1",
    sub={ name="Kali", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
    back={ name="Intarabus's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Store TP"+10',}},
    hands={ name="Merlinic Dastanas", augments={'Pet: Accuracy+30 Pet: Rng. Acc.+30','Blood Pact Dmg.+10','Pet: DEX+3','Pet: Mag. Acc.+2',}},
    back={ name="Sucellos's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','"Dbl.Atk."+10',}},
    body={ name="Ros. Jaseran +1", augments={'Path: A',}},
    range="Daurdabla",
    range="Marsyas",
    sub={ name="Barfawc", augments={'Path: C',}},
    legs="Fili Rhingrave +1",
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    left_ear="Odnowa Earring",
    left_ear="Odnowa Earring +1",
    body="Theo. Bliaut +3",
    neck="Erra Pendant",
    left_ring="Mephitas's Ring",
    left_ring="Mephitas's Ring +1",
    left_ear="Calamitous Earring",
    sub="Bolelabunga",
    sub="Daybreak",
    waist="Anrin Obi",
    left_ring="Freke Ring",
    sub={ name="Gada", augments={'Enh. Mag. eff. dur. +6','"Mag.Atk.Bns."+12',}},
    sub="Sucellus",
    sub="Vadose Rod",
    sub="Raetic Rod +1",
    main={ name="Arka II", augments={'Light Affinity: Magic Accuracy+6 Light Affinity: Recast time-14%','Light Affinity: Magic Damage+1',}},
    main={ name="Akademos", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    main="Tupsimati",
    main="Hvergelmir",
    main="Raetic Staff +1",
    ammo="Ghastly Tathlum +1",
    head="Mall. Chapeau +2",
    hands="Raetic Bangles +1",
    legs="Acad. Pants +1",
    neck={ name="Argute Stole +2", augments={'Path: A',}},
    neck="Baetyl Pendant",
    waist="Karin Obi",
    waist="Rairin Obi",
    waist="Korin Obi",
    left_ring="Mallquis Ring",
    left_ring={ name="Metamor. Ring +1", augments={'Path: A',}},
    head={ name="Telchine Cap", augments={'Mag. Acc.+23','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    body={ name="Telchine Chas.", augments={'Mag. Acc.+24','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    hands={ name="Telchine Gloves", augments={'Mag. Acc.+22','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    legs={ name="Telchine Braconi", augments={'Mag. Acc.+25','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    feet={ name="Telchine Pigaches", augments={'Mag. Acc.+24','"Fast Cast"+5','Enh. Mag. eff. dur. +10',}},
    head="Acad. Mortar. +3",
    hands="Acad. Bracers +3",
    legs={ name="Peda. Pants +3", augments={'Enhances "Tabula Rasa" effect',}},
    feet="Acad. Loafers +3",
    feet={ name="Peda. Loafers +3", augments={'Enhances "Stormsurge" effect',}},
    left_ring="Rahab Ring",
    left_ring="Jhakri Ring",
    left_ring="Locus Ring",
    left_ring="Mujin Band",
    main={ name="Musa", augments={'Path: C',}},
    body="Acad. Gown +3",
    head={ name="Peda. M.Board +3", augments={'Enh. "Altruism" and "Focalization"',}},
    head="Arbatel Bonnet +1",
    body={ name="Peda. Gown +3", augments={'Enhances "Enlightenment" effect',}},
    body="Arbatel Gown +1",
    hands="Arbatel Bracers +1",
    legs="Arbatel Pants +1",
    feet="Arbatel Loafers +1",
    back={ name="Bookworm's Cape", augments={'INT+1','MND+1','Helix eff. dur. +20','"Regen" potency+10',}},
    sub="Thrace Strap",
    left_ring="Sheltered Ring",
    back={ name="Lugh's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Haste+10',}},
    back={ name="Lugh's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Magic Damage +10','"Mag.Atk.Bns."+10',}},
    head={ name="Merlinic Hood", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Magic burst dmg.+10%','INT+4','Mag. Acc.+7',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+22 "Mag.Atk.Bns."+22','Magic burst dmg.+9%','DEX+1','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    left_ear={ name="Moonshade Earring", augments={'"Mag.Atk.Bns."+4','TP Bonus +250',}},
    left_ear="Static Earring",
    left_ring="Evanescence Ring",
    hands={ name="Otomi Gloves", augments={'HP+30','MP+30','MP+30',}},
    legs={ name="Chironic Hose", augments={'Accuracy+6','Pet: Mag. Acc.+22','"Refresh"+2','Mag. Acc.+4 "Mag.Atk.Bns."+4',}},
    hands="Bewegt Cuffs",
    waist="Hyorin Obi",
    waist="Furin Obi",
    waist="Dorin Obi",
    waist="Suirin Obi",
    sub="Relic Dagger",
    sub="Magnus Sword",
    sub="Ternion Dagger +1",
    sub={ name="Kanaria", augments={'"Store TP"+4','AGI+2','Accuracy+10','Attack+18','DMG:+12',}},
    main="Ishikirimaru",
    head="Ganesha's Mask",
    ammo="Sasuke Shuriken",
    head="Leth. Chappel +1",
    body="Lethargy Sayon +1",
    hands="Leth. Gantherots +1",
    legs="Leth. Fuseau +1",
    feet="Leth. Houseaux +1",
    body="Atrophy Tabard +3",
    hands="Atrophy Gloves +3",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body={ name="Viti. Tabard +3", augments={'Enhances "Chainspell" effect',}},
    hands={ name="Viti. Gloves +3", augments={'Enhancing Magic duration',}},
    legs={ name="Viti. Tights +3", augments={'Enspell Damage','Accuracy',}},
    feet={ name="Vitiation Boots +3", augments={'Immunobreak Chance',}},
    sub="Maxentius",
    head="Wh. Rarab Cap +1",
    waist="Chaac Belt",
    sub="Pukulatmuj",
    sub="Pukulatmuj +1",
    sub={ name="Colada", augments={'Enh. Mag. eff. dur. +4','Mag. Acc.+7','"Mag.Atk.Bns."+10',}},
    range="Ullr",
    ammo="Yetshila +1",
    head="Atro. Chapeau +1",
    neck={ name="Dls. Torque +2", augments={'Path: A',}},
    back={ name="Sucellos's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','Weapon skill damage +10%',}},
    legs="Shedir Seraweels",
    neck="Nodens Gorget",
    left_ear="Snotra Earring",
    legs="Atrophy Tights +1",
    sub="Naegling",
    neck="Anu Torque",
    waist="Sailfi Belt +1",
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    sub={ name="Crocea Mors", augments={'Path: C',}},
    sub={ name="Thibron", augments={'TP Bonus +1000',}},
    sub={ name="Beatific Shield +1", augments={'Phys. dmg. taken -4%','"Shield Mastery"+3','Magic dmg. taken -4%',}},
    feet={ name="Taeon Boots", augments={'Mag. Acc.+19','"Dual Wield"+5','DEX+10',}},
    neck="Ainia Collar",
    left_ring="Chirich Ring +1",
    head="Jhakri Coronal +2",
    body="Jhakri Robe +2",
    hands="Jhakri Cuffs +2",
    legs="Jhakri Slops +2",
    feet="Jhakri Pigaches +2",
    sub="Qutrub Knife",
    feet={ name="Merlinic Crackows", augments={'"Mag.Atk.Bns."+17','Pet: "Dbl. Atk."+2','"Treasure Hunter"+2','Accuracy+8 Attack+8',}},
    left_ear="Sherida Earring",
    left_ear="Darkside Earring",
    left_ear="Cryptic Earring",
    left_ring="Epaminondas's Ring",
    sub={ name="Malevolence", augments={'INT+10','Mag. Acc.+10','"Mag.Atk.Bns."+10','"Fast Cast"+5',}},
    head={ name="Fu. Bandeau +3", augments={'Enhances "Battuta" effect',}},
    head="Rune. Bandeau +3",
    head="Turms Cap +1",
    head="Halitus Helm",
    head="Erilaz Galea +1",
    body="Runeist's Coat +3",
    body={ name="Futhark Coat +3", augments={'Enhances "Elemental Sforzo" effect',}},
    head={ name="Adhemar Bonnet +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body={ name="Adhemar Jacket +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    body="Emet Harness +1",
    body={ name="Taeon Tabard", augments={'"Fast Cast"+5','Phalanx +3',}},
    hands="Meg. Gloves +2",
    hands="Turms Mittens +1",
    hands={ name="Taeon Gloves", augments={'Phalanx +3',}},
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    hands="Kurys Gloves",
    legs={ name="Futhark Trousers +3", augments={'Enhances "Inspire" effect',}},
    legs="Meg. Chausses +2",
    legs={ name="Taeon Tights", augments={'Phalanx +3',}},
    legs="Eri. Leg Guards +1",
    feet="Meg. Jam. +2",
    hands={ name="Rawhide Gloves", augments={'HP+50','Accuracy+15','Evasion+20',}},
    feet="Erilaz Greaves +1",
    neck={ name="Futhark Torque +2", augments={'Path: A',}},
    neck="Moonlight Necklace",
    waist="Ioskeha Belt +1",
    waist="Engraved Belt",
    back={ name="Ogma's Cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Enmity+10','Damage taken-5%',}},
    back={ name="Evasionist's Cape", augments={'Enmity+4','"Embolden"+15','"Dbl.Atk."+1','Damage taken-2%',}},
    left_ring="Niqmaddu Ring",
    main="Epeolatry",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs="Malignance Tights",
    feet="Malignance Boots",
    head={ name="Carmine Mask +1", augments={'Accuracy+20','Mag. Acc.+12','"Fast Cast"+4',}},
    body={ name="Carm. Sc. Mail +1", augments={'Attack+20','"Mag.Atk.Bns."+12','"Dbl.Atk."+4',}},
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Carmine Greaves +1", augments={'Accuracy+12','DEX+12','MND+20',}},
    sub="Utu Grip",
    ammo="Sapience Orb",
    ammo="Knobkierrie",
    waist="Ocean Sash",
    left_ear="Earthcry Earring",
    left_ear="Brutal Earring",
    left_ear="Suppanomimi",
    waist="Kasiri Belt",
    feet={ name="Taeon Boots", augments={'Spell interruption rate down -10%','Phalanx +3',}},
    feet="Turms Leggings +1",
    neck="Stone Gorget",
    waist="Gishdubar Sash",
    back="Moonbeam Cape",
    left_ring="Chirich Ring +1",
    sub="Khonsu",
    left_ring="Moonlight Ring",
    body={ name="Samnuha Coat", augments={'Mag. Acc.+12','"Mag.Atk.Bns."+12','"Dual Wield"+3',}},
    legs="Jokushu Haidate",
    waist="Orpheus's Sash",
    waist="Flume Belt +1",
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear="Halasz Earring",
    left_ear="Ishvara Earring",
    left_ear="Eabani Earring",
    head={ name="Taeon Chapeau", augments={'Accuracy+22','"Triple Atk."+2','Phalanx +3',}},
    left_ring="Gere Ring",
    left_ring="Ilabrat Ring",
    left_ring="Dingir Ring",
    legs={ name="Rawhide Trousers", augments={'MP+50','"Fast Cast"+5','"Refresh"+1',}},
    ammo="Yamarang",
    hands={ name="Futhark Mitons +1", augments={'Enhances "Sleight of Sword" effect',}},
    hands="Runeist Mitons +1",
    feet={ name="Futhark Boots +1", augments={'Enhances "Rayke" effect',}},
    feet="Runeist Bottes +1",
    legs={ name="Samnuha Tights", augments={'STR+10','DEX+10','"Dbl.Atk."+3','"Triple Atk."+3',}},
    waist="Audumbla Sash",
    sub="Mensch Strap +1",
    ammo="Aurgelmir Orb +1",
}