send_command('bind #` input //send @others /ja "ハートオブソラス" <me>')

send_command('bind #1 input //send @others /ma "ケアルIII" <t>')
send_command('bind #2 input //send @others /ma "ケアルIV" <t>')
send_command('bind #3 input //send @others /ma "ケアルV" <t>')
send_command('bind #4 input //send @others /ma "ケアルガII" <t>')
send_command('bind #5 input //send @others /ma "ケアルガIII" <t>')
send_command('bind #6 input //send @others /ma "極光の陣" <me>')

send_command('bind #7 input //send @others /ma "ディアII" <t>')
send_command('bind #8 input //send @others /ma "サイレス" <t>')
send_command('bind #9 input //send @others /ma "パライズ" <t>')
send_command('bind #0 input //send @others /ma "ディスペル" <t>')

send_command('bind #q input //send @others /ma "白のグリモア" <me>')
send_command('bind #w input //send @others /ma "アスピル" <t>')
send_command('bind #e input //send @others /ma "ヘイスト" <t>')
send_command('bind #r input //send @others /ma "リフレシュ" <t>')
send_command('bind #t input //send @others /ma "ブリンク" <me>')
send_command('bind #y input //send @others /ma "ファランクス" <me>')
send_command('bind #u input //send @others /ma "ストンスキン" <me>')
send_command('bind #i input //send @others /ma "アクアベール" <me>')
send_command('bind #o input //send @others /ma "リジェネIV" <t>')
send_command('bind #p input //send @others /ja "机上演習" <me>')

send_command('bind #, input //send @others /ma "スニーク" <t>')
send_command('bind #. input //send @others /ma "インビジ" <t>')
send_command('bind #[ input //send @others /ja "女神降臨の章" <me>')
send_command('bind #] input //send @others /ja "女神の愛撫" <me>')

send_command('bind #numpad7 input //send @others /ma "パラナ" <t>')
send_command('bind #numpad8 input //send @others /ma "サイレナ" <t>')
send_command('bind #numpad9 input //send @others /ma "ブライナ" <t>')
send_command('bind #numpad4 input //send @others /ma "ポイゾナ" <t>')
send_command('bind #numpad5 input //send @others /ma "ストナ" <t>')
send_command('bind #numpad6 input //send @others /ma "ウィルナ" <t>')
send_command('bind #numpad1 input //send @others /ma "カーズナ" <t>')
send_command('bind #numpad2 input //send @others /ma "カーズナ" Gary')
send_command('bind #numpad+ input //send @others /ma "イレース" <t>')
send_command('bind #numpad0 input //send @others /ma "サクリファイス" <t>')
send_command('bind #numpad. input //send @others /ma "エスナ" <me>')